Add some static types
godotengine/godot-demo-projects pull request #1008
Opened 2024-01-03 05:51 UTC by MatrixFrog

2024-01-07 09:20 UTC, dalexeev reviewed
Please add type hints for the `_ready()` and `_process()` functions in `character.gd`, `_ready()` and `_draw()` in `pathfind_astar.gd`, and unused parameter `_delta`. Also please add type hints or at least type inference for local variables `last_point` and `current_point` in `_draw()`.

2024-01-07 09:20 UTC, dalexeev commented on 2d/navigation_astar/character.gd
> +@onready var _tile_map: PathFindAStar = $"../TileMap"
It might be better to remove `class_name` from `pathfind_astar.gd` and add `const`-`preload`:

```gdscript
const PathFindAStar = preload("./pathfind_astar.gd")
```

2024-01-08 01:20 UTC, MatrixFrog commented on 2d/navigation_astar/character.gd
> +@onready var _tile_map: PathFindAStar = $"../TileMap"
ok nice i didn't realize that would do effectively the same thing

2024-01-08 10:58 UTC, dalexeev approved these changes
The changes look good to me, but I'm not sure we've reached consensus on #868. Personally, I support static typing in demo projects and find it improves readability. However, I recognize the concerns and think we should first define the rules for using static typing in demo projects.

There are also questions about type inference if the initializer does not contain the type name and whether it is necessary to specify the type for `for` loop variables (a new feature in 4.2).

2024-08-27 12:28 UTC, aaronfranke requested changes
When the type is not written on the same line, it should be explicitly specified. https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#inferred-types

2024-08-27 12:28 UTC, aaronfranke commented on 2d/navigation_astar/character.gd
> +	var arrived_to_next_point := _move_to(_next_point)
```suggestion
	var arrived_to_next_point: bool = _move_to(_next_point)
```

2024-08-27 12:28 UTC, aaronfranke commented on 2d/navigation_astar/character.gd
> +	var steering := desired_velocity - _velocity
```suggestion
	var desired_velocity: Vector2 = (local_position - position).normalized() * speed
	var steering: Vector2 = desired_velocity - _velocity
```

2024-08-27 12:28 UTC, aaronfranke commented on 2d/navigation_astar/pathfind_astar.gd
> +	var map_position := local_to_map(local_position)
```suggestion
func is_point_walkable(local_position: Vector2) -> bool:
	var map_position: Vector2 = local_to_map(local_position)
```

2024-08-27 12:28 UTC, aaronfranke commented on 2d/navigation_astar/pathfind_astar.gd
> +	var last_point := _path[0]
```suggestion
	var last_point: Vector2 = _path[0]
```

2024-08-27 12:28 UTC, aaronfranke commented on 2d/navigation_astar/pathfind_astar.gd
> +		var current_point := _path[index]
```suggestion
		var current_point: Vector2 = _path[index]
```

2024-08-28 03:25 UTC, MatrixFrog commented
Thanks. I should have time to test this out in a couple days.

2024-08-28 07:02 UTC, dalexeev commented on 2d/navigation_astar/character.gd
```diff
-@export_range(10, 500, 0.1, "or_greater") var speed := 200.0
+@export_range(10.0, 500.0, 0.1, "or_greater") var speed: float = 200.0
```

2024-08-29 23:23 UTC, MatrixFrog commented
ok just tested it out, this seems to be working well and should be ready to merge! thanks!

2024-08-30 01:05 UTC, aaronfranke approved these changes
I didn't test this but it looks correct.

2024-08-31 01:48 UTC, Calinou approved these changes
Tested locally, it works as expected.

Thanks!

2024-08-31 01:48 UTC, merged