Updated pong
godotengine/godot-demo-projects pull request #1071
Opened 2024-06-08 06:31 UTC by Insane96

## Scene
The scene had some problems:
All the collision node were twice as small as they should have. Not sure if it's due to an update in the engine.
![image](https://github.com/godotengine/godot-demo-projects/assets/7185104/6e691460-1253-4731-abf3-a7c49c67cb38)
So the collisions are now bigger (2x exactly) to cover the whole sprite, and I've changed the ball collision shape to a sphere.

## Ceiling and Floor
The ceiling was just transposing the angle of the ball by 90°, I've changed it to actually bounce back.

## Paddle
The paddles have been made faster in movement (+50%) and now bounce the ball back based off the position of the collision.

## Ball
Ball now speeds up faster and picks a new random direction and angle when the game starts or resets.

2024-06-10 13:46 UTC, paulloz requested changes

2024-06-10 13:46 UTC, paulloz commented on mono/pong/Logic/Paddle.cs
Use 4 spaces (no tabs) to indent[^1].

[^1]: https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_style_guide.html#formatting

2024-06-12 08:08 UTC, Insane96 commented
Applied all request changes

2024-06-12 11:50 UTC, aaronfranke requested changes
None of these changes can be considered or accepted unless the same changes are made to the GDScript version of the demo.

2024-06-12 11:50 UTC, aaronfranke commented on mono/pong/Logic/Ball.cs
> +    private readonly Random _random = new();
Target-typed `new` is only available in C# 9 or later. For the sake of keeping the demo's code compatible with older C# versions, we should not use it.

Keep in mind that even if Godot supports C# 9 or later, there are older Godot versions that do not. There is value in keeping the code consistent between all versions of the demo, even with the 3.x versions. That isn't to say that we don't want to improve things over time, just avoid unnecessary changes that don't affect behavior but do negatively affect compatibility.

2024-06-12 13:07 UTC, AThousandShips commented on mono/pong/Logic/Ball.cs
> +        Direction = this.NewRandomDirection();
Are all the added `this` really necessary? What are they disambiguating?

2024-06-12 13:42 UTC, paulloz commented on mono/pong/Logic/Ball.cs
> +        Direction = this.NewRandomDirection();
Thanks, I missed those when I reviewed.

2024-06-13 19:02 UTC, paulloz commented
> None of these changes can be considered or accepted unless the same changes are made to the GDScript version of the demo.

The purely corrective parts (area sizes in the `.tscn`, and the typo fixed in `Paddle.cs`) could. But otherwise, yes.

2024-06-13 19:08 UTC, AThousandShips commented
Even those changes to the shapes don't match the gdscript version so they should match

2024-06-27 09:03 UTC, closed without merging