Fix updated Android IAP project in c#
godotengine/godot-demo-projects pull request #1105
Opened 2024-08-24 14:33 UTC by JavierStark

After my previous update of the project [#1104] to port it to Godot 4.3 and adapt the code to the new API, I found that it failed to work on build. 

I used debug from mobile device and I found that the app was unable to access certain dynamic libraries for some reason.

Despite this, one of my personal projects were I was using this code worked perfectly well so I thought it was something related to the version of the [GodotBillingPlugin](https://github.com/godotengine/godot-google-play-billing) used. 
I added the last version 1.2.0 and reconstructed the project just in case it was something else and I finally could get it working.

Moreover, I fixed a problem with signal strings that I found after connecting the app with Google Play and setting up everything needed to do purchases.

2024-08-24 14:35 UTC, JavierStark commented
There have some problem with the PR. Sorry for that. I'm learning to do them properly

2024-08-24 22:19 UTC, Calinou approved these changes
Thanks!

2024-08-24 22:19 UTC, Calinou commented on mono/android_iap/project.godot
> +textures/vram_compression/import_etc2_astc=true
Please change this back to Compatibility, as that rendering method works better on most mobile devices (including low-end ones).

This is because the mobile rendering method uses Vulkan, and many mobile devices don't support it (or poorly).

2024-08-27 12:22 UTC, aaronfranke requested changes

2024-08-28 10:37 UTC, JavierStark commented on mono/android_iap/GodotGooglePlayBilling/GooglePlayBilling.cs
> -                _payment.Connect(SignalName.Connected, Callable.From(OnGodotGooglePlayBilling_connected)); // No params
I understand what you mean and that's what I tried to do first but I believe that's not possible in this situation.
`_payment` the GodotGooglePlayBilling singleton which comes from the Android plugin.
And that plugin is made with Java ([link to the repo](https://github.com/godotengine/godot-google-play-billing/tree/master)).
If we go to the code of the plugin we can find the following lines:
`emitSignal("query_purchases_response", (Object)returnValue);`
`emitSignal("connected");`
etc.

That's is the signal emission with the name of the signal hardcoded in Java. So I don't believe it's available in any way using SignalName.
I may be missing something but that's what I know so far.

2024-08-28 23:58 UTC, aaronfranke approved these changes

2024-08-28 23:58 UTC, merged