[WIP] Add a saving/loading demo with various serialization formats
godotengine/godot-demo-projects pull request #517
Opened 2020-09-07 20:07 UTC by Calinou

This demo showcases how to save a simple game with each serialization format supported by Godot.

2020-10-21 07:02 UTC, aaronfranke requested changes

2020-10-21 07:02 UTC, aaronfranke commented on misc/save_load/player.gd
> +	position += motion
The motion overcomplicates the demo, and also you currently aren't saving the motion anyway, just the position.

```suggestion
	var velocity = Vector2.ZERO
	velocity.x = Input.get_action_strength("move_right") - Input.get_action_strength("move_left")
	velocity.y = Input.get_action_strength("move_down") - Input.get_action_strength("move_up")
	position += velocity * MOVE_SPEED * delta
```

2020-12-09 15:06 UTC, Calinou commented
I applied the suggestions, removed reference to documentation not available yet and added a screenshot.

2020-12-12 22:24 UTC, aaronfranke requested changes
I think this should be moved to the `2d/` folder. While this isn't a demo "for 2D", it is a demo that uses Node2D, and I moved similar demos such as Instancing and Tween to that folder.

2020-12-12 22:24 UTC, aaronfranke commented on misc/save_load/README.md
> +
```suggestion

For more information, see this documentation article:
https://docs.godotengine.org/en/latest/tutorials/io/saving_games.html

```

2020-12-12 22:24 UTC, aaronfranke commented on misc/save_load/enemy.gd
> +func _on_AttackArea_body_entered(body: Node) -> void:
For now the demos don't use static types per Akien's request.

```suggestion
func _on_AttackArea_body_entered(body):
```

2020-12-12 22:24 UTC, aaronfranke commented on misc/save_load/enemy.gd
> +func _on_AttackArea_body_exited(_body: Node) -> void:
```suggestion
func _on_AttackArea_body_exited(_body):
```

2020-12-12 22:24 UTC, aaronfranke commented on misc/save_load/save_load_config_file.gd
> +
```suggestion
# This script shows how to save data using Godot's custom ConfigFile format.
# ConfigFile can store any Godot type natively.

```

2020-12-12 22:24 UTC, aaronfranke commented on misc/save_load/save_load_json.gd
> +
```suggestion
# This script shows how to save data using the JSON file format.
# JSON is a widely used file format, but not all Godot types can be
# stored natively. For example, integers get converted into doubles,
# and to store Vector2 and other Variant types you need `var2str()`.

```

2020-12-12 22:44 UTC, aaronfranke requested changes
Looks good, but there is one last (fairly important) thing: The `screenshots/` folder is missing a `.gdignore` file. We should add one to prevent Godot from importing `screenshots/save_load.png`.

2020-12-12 23:21 UTC, Calinou commented
@aaronfranke The option appears to be enabled here:

![image](https://user-images.githubusercontent.com/180032/101999034-261df780-3cd9-11eb-933c-25bd86654ceb.png)

2020-12-12 23:26 UTC, aaronfranke approved these changes
> The option appears to be enabled here:

Weird, maybe you have something on your account that prevents it? All I know is that I can't push to your repo.

2020-12-12 23:27 UTC, merged