Re-write the navigation path-following code to be easier to read + add comments
godotengine/godot-demo-projects pull request #540
Opened 2020-10-15 19:09 UTC by jak-sdk

Hi,

I found the previous code that implemented the navmesh path following to be quite complex and a little difficult to follow.
I've tried to simplify it as much as I can and document what does what, and any considerations that went into it.

As far as I can tell it behaves identically to the previous code, I appreciate any second opinions though!

Please let me know if this is ok / if I've added too many comments, or any other recommendations.
I'm hoping this will be more approachable for newcomers to Godot.

Thanks,
Jak

2020-10-15 19:37 UTC, aaronfranke requested changes

2020-10-15 19:37 UTC, aaronfranke commented on 3d/navmesh/navmesh.gd
> +func draw_path(path):
Function declaration of 'draw_path()' conflicts with a variable of the same name.

The local variable 'path' is shadowing an already-defined variable at line 8.

2020-10-15 19:37 UTC, aaronfranke commented on 3d/navmesh/navmesh.gd
> +    m.albedo_color = Color.white
Tabs are used for indentation in GDScript.

2020-10-16 08:23 UTC, aaronfranke requested changes

2020-10-16 08:23 UTC, aaronfranke commented on 3d/navmesh/navmesh.gd
> +		robot.transform = robot.transform.looking_at(look_at_point, Vector3(0,1,0))
```suggestion
		robot.transform = robot.transform.looking_at(look_at_point, Vector3.UP)
```

2020-10-16 08:23 UTC, aaronfranke commented on 3d/navmesh/navmesh.gd
> +		# otherwise we would go past it, and potentially through a wall or over a cliff edge!
Please use proper sentence capitalization and punctuation. We should also try to avoid going over 80 characters wide in a single line. While shortening comments, if you can make the lines similar in length that would be ideal (else the last line should be shortest). For example, here I would do this:

```suggestion
		# If the next node is closer than we intend to 'step', then
		# take a smaller step. Otherwise we would go past it and
		# potentially go through a wall or over a cliff edge!
```

2020-10-16 08:23 UTC, aaronfranke commented on 3d/navmesh/navmesh.gd
> +		#	and where we want to go
Here you have a tab inside the comment, which is bad. There is one other instance in this file.

2020-10-16 08:25 UTC, jak-sdk commented on 3d/navmesh/navmesh.gd
> +    m.albedo_color = Color.white
Sorry, I hadn't noticed my script editor had silently converted the whole thing to spaces..

2020-10-16 08:26 UTC, jak-sdk commented on 3d/navmesh/navmesh.gd
> +		# otherwise we would go past it, and potentially through a wall or over a cliff edge!
Ok, I'll commit this and apply a similar approach to the other comments, thanks

2020-10-16 08:27 UTC, jak-sdk commented on 3d/navmesh/navmesh.gd
> +		#	and where we want to go
Whoops.. Clearly some over zealous find and replace..

2020-10-16 16:29 UTC, aaronfranke requested changes

2020-10-16 16:29 UTC, aaronfranke commented on 3d/navmesh/navmesh.gd
> +		# Note: for a kinetic body we would instead use move_and_slide
```suggestion
		# Note: For a KinematicBody, we would instead use move_and_slide
```

2020-10-16 16:29 UTC, aaronfranke commented on 3d/navmesh/navmesh.gd
> +		# Lastly lets make sure we're looking in the direction we're travelling.
```suggestion
		# Lastly let's make sure we're looking in the direction we're traveling.
```

2020-10-16 16:55 UTC, aaronfranke requested changes

2020-10-16 16:55 UTC, aaronfranke commented on 3d/navmesh/navmesh.gd
> +		robot.transform = robot.transform.looking_at(look_at_point, Vector3.UP)
This code currently causes an error when pathing finishes, since `look_at_point` is the same as translation. This is due to `direction.normalized()` being zero. The fix here is to just check `if direction` to see if it's a non-zero vector. Note that we can't move this check anywhere else since we still need to process a Y-only movement, just not rotate for it. Also, Spatial has a shortcut for `robot.transform = robot.transform.looking_at`, we can just use `robot.look_at`.

```suggestion
		if direction:
			# Direction is relative, so apply it to the robot's location to
			# get a point we can actually look at.
			var look_at_point = robot.translation + direction.normalized()
			# Make the robot look at the point.
			robot.look_at(look_at_point, Vector3.UP)
```

2020-10-16 17:43 UTC, jak-sdk commented on 3d/navmesh/navmesh.gd
> +		robot.transform = robot.transform.looking_at(look_at_point, Vector3.UP)
Thanks, that's a good point.

2020-10-16 18:02 UTC, aaronfranke commented
The code looks good, and is a huge improvement in both readability and simplicity, thank you. The only thing left is to clean up the Git history and squash the commits into one. See [this documentation article](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) for more information. If you can't figure it out, GitHub does have a squash and merge feature, but it destroys history so it's better if the PR author does it.

2020-10-16 18:56 UTC, jak-sdk commented
Thanks :smile: 
I've squashed the commits, let me know if it's ok. 
Happy to have helped, in all honesty the demo as it was definitely helped me but I wanted to add comments and thought a little refactoring was worth doing too.
Thank you very much for your guidance and your help improving my code.

2020-10-16 18:56 UTC, aaronfranke approved these changes

2020-10-16 18:57 UTC, merged

2020-10-16 18:59 UTC, aaronfranke commented
Thanks!

One other thing, for next time, it's best practice to create a separate branch when making a PR, instead of just using master.