A Full List of Demos That have UI
godotengine/godot-demo-projects pull request #548
Opened 2020-11-04 20:07 UTC by Mr-K-GameDev

Made a Full list of All of the Demos That have Control Nodes in them **Except the gui Folder ones**, 
and also the ones that don't, and put them in a .txt file,

Took me some time to do, But i did it, Also, I made Links to Demos that have for example A Pause Menu or a Main Menu ect...

2020-11-04 20:45 UTC, Calinou commented
I'm not sure if having such a list is useful. Each demo has a description that can be read in a matter of seconds already.

2020-11-04 20:52 UTC, Mr-K-GameDev commented
@Calinou yes.... but Do you know where to find a Demo in this Repo?
With out taking quiet abit of time to do so

2020-11-04 20:52 UTC, aaronfranke commented
I'm not sure this is really a useful list. First of all, making this list comprehensive is a really difficult task. Why list every single node type for Operating System Testing, but not for Voxel Game? Why make this list for UI nodes but not for other nodes, like 2D and 3D nodes, or other types of nodes like AnimationTree?

Second of all, whatever the goal is, there are better ways to accomplish this than making a huge list like this. If you want to find demos that are good for demonstrating a particular node, a better idea is to [link demos in the class reference](https://github.com/godotengine/godot/pull/42486). If you want to find demos with *any instance of a particular node*, you can just use recursive grep:

```
$ grep -RIn GridContainer
2d/role_playing_game/screens/combat/interface/UI.gd:20: $Buttons/GridContainer/Attack.grab_focus()
2d/role_playing_game/screens/combat/Combat.tscn:50:[node name="GridContainer" type="GridContainer" parent="UI/Buttons"]
2d/role_playing_game/screens/combat/Combat.tscn:59:[node name="Attack" type="Button" parent="UI/Buttons/GridContainer"]
2d/role_playing_game/screens/combat/Combat.tscn:66:[node name="Defend" type="Button" parent="UI/Buttons/GridContainer"]
2d/role_playing_game/screens/combat/Combat.tscn:74:[node name="Flee" type="Button" parent="UI/Buttons/GridContainer"]
2d/role_playing_game/screens/combat/Combat.tscn:81:[connection signal="button_up" from="UI/Buttons/GridContainer/Attack" to="UI" method="_on_Attack_button_up"]
2d/role_playing_game/screens/combat/Combat.tscn:82:[connection signal="button_up" from="UI/Buttons/GridContainer/Defend" to="UI" method="_on_Defend_button_up"]
2d/role_playing_game/screens/combat/Combat.tscn:83:[connection signal="button_up" from="UI/Buttons/GridContainer/Flee" to="UI" method="_on_Flee_button_up"]
networking/webrtc_signaling/demo/main.tscn:66:[node name="Clients" type="GridContainer" parent="VBoxContainer"]
3d/voxel/menu/options/options.tscn:32:[node name="OptionButtons" type="GridContainer" parent="VBoxContainer/OptionsBackground"]
misc/os_test/os_test.tscn:72:[node name="GridContainer" type="GridContainer" parent="HBoxContainer/Actions"]
misc/os_test/os_test.tscn:83:[node name="OpenShellWeb" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:90:[node name="OpenShellFolder" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:98:[node name="ChangeWindowTitle" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:106:[node name="ChangeWindowIcon" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:115:[node name="MoveWindowToForeground" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:123:[node name="RequestAttention" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:132:[node name="VibrateDeviceShort" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:140:[node name="VibrateDeviceLong" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:149:[node name="AddGlobalMenuItems" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:157:[node name="RemoveGlobalMenuItem" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:166:[node name="GetClipboard" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:174:[node name="SetClipboard" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:183:[node name="DisplayAlert" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:191:[node name="KillCurrentProcess" type="Button" parent="HBoxContainer/Actions/GridContainer"]
misc/os_test/os_test.tscn:201:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/OpenShellWeb" to="HBoxContainer/Actions" method="_on_OpenShellWeb_pressed"]
misc/os_test/os_test.tscn:202:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/OpenShellFolder" to="HBoxContainer/Actions" method="_on_OpenShellFolder_pressed"]
misc/os_test/os_test.tscn:203:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/ChangeWindowTitle" to="HBoxContainer/Actions" method="_on_ChangeWindowTitle_pressed"]
misc/os_test/os_test.tscn:204:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/ChangeWindowIcon" to="HBoxContainer/Actions" method="_on_ChangeWindowIcon_pressed"]
misc/os_test/os_test.tscn:205:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/MoveWindowToForeground" to="HBoxContainer/Actions" method="_on_MoveWindowToForeground_pressed"]
misc/os_test/os_test.tscn:206:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/RequestAttention" to="HBoxContainer/Actions" method="_on_RequestAttention_pressed"]
misc/os_test/os_test.tscn:207:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/VibrateDeviceShort" to="HBoxContainer/Actions" method="_on_VibrateDeviceShort_pressed"]
misc/os_test/os_test.tscn:208:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/VibrateDeviceLong" to="HBoxContainer/Actions" method="_on_VibrateDeviceLong_pressed"]
misc/os_test/os_test.tscn:209:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/AddGlobalMenuItems" to="HBoxContainer/Actions" method="_on_AddGlobalMenuItems_pressed"]
misc/os_test/os_test.tscn:210:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/RemoveGlobalMenuItem" to="HBoxContainer/Actions" method="_on_RemoveGlobalMenuItem_pressed"]
misc/os_test/os_test.tscn:211:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/GetClipboard" to="HBoxContainer/Actions" method="_on_GetClipboard_pressed"]
misc/os_test/os_test.tscn:212:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/SetClipboard" to="HBoxContainer/Actions" method="_on_SetClipboard_pressed"]
misc/os_test/os_test.tscn:213:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/DisplayAlert" to="HBoxContainer/Actions" method="_on_DisplayAlert_pressed"]
misc/os_test/os_test.tscn:214:[connection signal="pressed" from="HBoxContainer/Actions/GridContainer/KillCurrentProcess" to="HBoxContainer/Actions" method="_on_KillCurrentProcess_pressed"]
misc/joypads/joypads.tscn:587:[node name="ButtonGrid" type="GridContainer" parent="Buttons"]
```

2020-11-04 20:57 UTC, Mr-K-GameDev commented
well to answer your Question, I'll say this, Do you know.... any Game or any Good looking Demo, That doesn't use UI in them?

Ofcourse There isn't, So this is why i made this list For Control Nodes Only, because alot of Different Demos, Use UI in them.

2020-11-04 20:58 UTC, Mr-K-GameDev commented
while Other things like Shaders and 3D stuff Can go to there Folders In the Repo.

2020-11-04 21:03 UTC, Mr-K-GameDev commented
Also.... My guy, doing it this way, (Typing in a Node name) Won't help alot for Beginners or people how are looking for Examples

Most game Devs want to Look at a Demo, and see The nodes that are used, See How they are place/Connected.

2020-11-05 21:08 UTC, Mr-K-GameDev commented
I convert this PR to Draft to see if there's better ways of doing something in Script,
To imporve the Quality of the Code for UI Updates, Thanks alot if you guys gave me some Feed Back,
I'll listen Carfully through all of them and Update them when ever i could.

2020-11-05 23:51 UTC, aaronfranke commented
> Most game Devs want to Look at a Demo, and see The nodes that are used, See How they are place/Connected.

If the goal is to just list which things are in each demo, and see how they interact and are placed/connected, the *only* way for people to do this is to just open the demo. Describing how every node in a demo works is not feasible.

> to Find an Example, and some times the user just want a simple Link to go to The thing he/she Wanted, So We should try make things Simple, Easy to Understand/Go to.

That's the idea with linking demos from the class reference.

Honestly, I just don't see this as a problem, and your solution doesn't seem like something that would help. There is a general expectation that people who want to contribute to a repo should read some of the code already in the repo.

* If you had simply clicked on each of the category folders and read the names of the demos, in [the `misc` folder](https://github.com/godotengine/godot-demo-projects/tree/master/misc), you would have immediately noticed that [the `pause` folder](https://github.com/godotengine/godot-demo-projects/tree/master/misc/pause) exists, and then you wouldn't have created #547.

* If you had simply clicked on each of the demos in the `gui/` folder, you would have immediately seen [the screenshot](https://raw.githubusercontent.com/godotengine/godot-demo-projects/master/gui/drag_and_drop/screenshots/drag_and_drop.png) in the README for [Drag and Drop](https://github.com/godotengine/godot-demo-projects/tree/master/gui/drag_and_drop), and then you wouldn't have created #546.

If someone can't be bothered to read the name of a folder or READMEs in the folders, why would they read this list? I do not see this as a problem that 99.99% of people would have, and I do not think this list would actually help. This is not a discoverability problem, this is a problem with not putting in effort to learn the repository you're contributing to.

2020-11-06 00:03 UTC, Mr-K-GameDev commented
....... ok then, i'll just Update already existing Demos UI (If i could).... and call it a day
like... the only Goal i wanted.... is to give people Some Examples on GUI stuff in Godot.... That's all
*sigh*

2020-11-06 00:06 UTC, Mr-K-GameDev commented
because here is the thing.... if i made a Main Menu for example, You would say
"hay, Voxel Game Demo have a main menu, We should improve it instead of making Similer Demos"
Make a Settings Menu, "Voxel game Again"
VBoxContainer/HBoxContainer "JRPG Demo"
..... like... what do you want me to do? Why do you make it so Hard to Make Examples?

2020-11-06 00:08 UTC, Mr-K-GameDev commented
Any Control Node..... @aaronfranke Already a Demo with this node, Can't do
like... i think even if i went this far.... and gone ahead and made my Own Repo..... No body will know about it
and it's purpose will just to be there..... with no one knowing it even Exist!!

2020-11-06 00:11 UTC, Mr-K-GameDev commented
like.... all i want to do, is make Examples for other game devs, That's all
please give me a suggestion on how i can do this.... with out tell me
"Nope, a Demo already have this", if There's another Demo with this UI like..... so what
the more Examples, the better in my opinion

2020-11-06 00:33 UTC, Mr-K-GameDev commented
ok then...... i guess **it's progress time!**

2020-11-06 01:46 UTC, Mr-K-GameDev commented
No more Control Nodes List, Time to make some progress at Improving/Making Good UI Demos.
Also @aaronfranke I made a Suggestion (made a New Issue in the Issues Place) That the Tween Demo Needs a Complete Re-Work.
*Read the Issue for more Info*

2020-11-06 01:54 UTC, aaronfranke requested changes
Making the font size bigger and adding a coin counter are good ideas, but there are a few issues as-is.

The coin counter is a bit distracting, since it's the largest animated thing on the screen. Perhaps the coin counter should be moved to the pause menu, so that it's not visible until the game is paused?

![Screenshot from 2020-11-05 20-50-46](https://user-images.githubusercontent.com/1646875/98316661-d5640200-1fa8-11eb-994d-e028928599ae.png)

Trying to quit from the pause menu in splitscreen doesn't work with this PR:

![Screenshot from 2020-11-05 20-45-19](https://user-images.githubusercontent.com/1646875/98316295-21fb0d80-1fa8-11eb-843c-02d81cf52d26.png)

Collecting coins in splitscreen doesn't work this PR:

![Screenshot from 2020-11-05 20-48-35](https://user-images.githubusercontent.com/1646875/98316388-52db4280-1fa8-11eb-8e22-5e1e9cb3ab78.png)

2020-11-06 01:54 UTC, aaronfranke commented on 2d/platformer/project.godot
> +quality/driver/driver_name="GLES2"
The demo needs to be GLES3 due to it using particles.

2020-11-06 02:46 UTC, Mr-K-GameDev commented
fixed the Crashing probleme when in SplitScreen mode, also you can Collect Coins.
now here is the thing.... idk if it's better to make for every Player have his Own Coins Counter
or to just have one Coins Counter for both?

2020-11-06 02:47 UTC, Mr-K-GameDev commented on 2d/platformer/project.godot
> +quality/driver/driver_name="GLES2"
For the time being, I'll use GLES2, Because my IGPU doesn't support GLES3 :(

2020-11-19 06:55 UTC, aaronfranke requested changes
The Platformer 2D demo looks pretty nice, but it still needs tweaking, and I need to look over the code in more detail. However, there are more pressing issues with this PR, so I will do that later.

For the Drag and Drop demo, the changes are a net negative. It's not good that all of the colors start as the same color, it means that you can't just start dragging and dropping right away, you have to change the colors first. We don't need a custom font, the default one works fine here. It's strange that the theme has a custom panel style, but then this is only used in one place, so it's really just for that node. The buttons shouldn't change size when you hover over them, instead they should just slightly increase in brightness. The orange colors in the color picker look atrocious, it's hard to read the white text on them, and the text shifts around due to the buttons changing size. Also, I don't see the need for a gradient on the background, a plain color would work fine (we should just use the background's clear color, no need to have a panel node or anything, if you want to tweak that color then you can do it in project settings).

I can't open the Tween demo with this PR. Godot freezes before I can get it open. However, if I delete the font (and we don't need a custom font here either), then I can open it. The changes to the Tween demo in this PR a net negative due to the fact that now not all of the buttons are displayed on screen. The background gradient should also be removed like I mentioned above.

> idk if it's better to make for every Player have his Own Coins Counter or to just have one Coins Counter for both?

It's good to have one counter for both, the game is co-op so it makes sense that the coins are counted in one place.

2020-11-19 06:55 UTC, aaronfranke commented on 2d/platformer/src/Actors/Player.gd
> +
```suggestion

```

2020-11-19 06:55 UTC, aaronfranke commented on 2d/platformer/src/UserInterface/CoinsCounter.tscn
> +"frames": [ SubResource( 2 ), SubResource( 3 ), SubResource( 4 ), SubResource( 5 ) ],
The coin in the menu doesn't work as expected right now, since the spinning animation makes the coin get "smaller" and then it teleports back to being "bigger", while it should gradually move between those states. You can fix this by adding the third and second frames to the end.

2020-11-19 06:55 UTC, aaronfranke commented on 2d/platformer/src/UserInterface/PauseMenu.gd
> +
```suggestion
```

2020-11-19 06:55 UTC, aaronfranke commented on 2d/platformer/src/UserInterface/PauseMenu.gd
> +
```suggestion
```

2020-11-19 06:55 UTC, aaronfranke commented on 2d/tween/main.gd
> +# Node References
```suggestion
```

2020-11-19 06:55 UTC, aaronfranke commented on 2d/tween/main.gd
> +# INITIALIZING Signals
```suggestion

```

2020-11-19 06:55 UTC, aaronfranke commented on 2d/tween/project.godot
> +window/size/test_height=648
```suggestion
```

2021-01-06 14:55 UTC, NathanLovato commented
@Mr-K-GameDev Moving forward, could you to do one PR per demo you change? It'll be much easier to give you focused feedback, and to merge changes or not. In this PR, there's a mix of changes we could merge and others we probably shouldn't.

Regarding the tween demo, I prefer the changes in #570, the demo, when you run it, looks cleaner. As mentioned there, in this demo's case, tidying the files and scenes doesn't feel too important.

I would see this kind of demo more like PhaserJS's demos, like, not something you would open in Godot, but rather something you'd run and test in a web browser. If you wanted to teach how to use tweens in your code, you'd need very different code.

2021-01-06 14:56 UTC, NathanLovato commented
I generally feel like @aaronfranke on these changes. The platformer ones look positive, the others not so much. Among other things, the visuals for the drag and drop and tween demos don't look great.

2021-01-06 22:42 UTC, closed without merging