Fixes and adjustments in 3D physics tests
godotengine/godot-demo-projects pull request #559
Opened 2020-12-12 00:23 UTC by pouleyKetchoupp

* Add Functional Test / Stack & Pyramid
For testing stack stability.

* Add Functional Test / Raycasts
Visually test raycast on different shapes.

* Fix leaks on exit
Some Nodes are copied and removed from the scene to be used as templates,
they need to be freed manually on exit.

* Fix Performance Test / Contacts
Positions adjusted, some shape types were not created at the center.

2020-12-12 02:47 UTC, pouleyKetchoupp commented
Added new test (Performance / Broadphase).

2020-12-12 10:28 UTC, aaronfranke requested changes

2020-12-12 10:28 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_raycasting.gd
> +	# draw raycast line.
```suggestion
	# Draw raycast line.
```

2020-12-12 10:28 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_raycasting.gd
> +	# draw raycast arrow.
```suggestion
	# Draw raycast arrow.
```

2020-12-12 10:28 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_pyramid.gd
> +		pos_y += box_size.y
The initial conditions of this test (and the box stack test) are "too perfect" to thoroughly test physics. It would be much better if the starting position wasn't already perfectly stacked. For example, changing this line to `pos_y += box_size.y * 2` makes the boxes start in the air and fall down, and *immediately* showcases a problem when run with Godot Physics.

2020-12-12 10:28 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_pyramid.gd
> +	var root_node = $Pyramid
A pyramid has a square base. What you have created here is a triangle :P

Not sure if we want to have a triangle test, a pyramid test, or both, but as-is this isn't good because the name is incorrect.

2020-12-12 14:40 UTC, pouleyKetchoupp commented on 3d/physics_tests/tests/functional/test_pyramid.gd
> +		pos_y += box_size.y
The main goal here is to test physics stability for stacking, without necessarily adding extra forces to the equation. You can set a higher pyramid and you'll showcase a problem already.

I'll add a separation between boxes as an option though, it's a good idea to allow the possibility to test more cases.

2020-12-12 14:41 UTC, pouleyKetchoupp commented on 3d/physics_tests/tests/functional/test_pyramid.gd
> +	var root_node = $Pyramid
You can see it as a 2D pyramid too :)

Actually, this scene does both. If you set a max depth of 100 you'll get an actual 3D pyramid. I haven't made that the default because it was running extremely slowly with too many rigid bodies.

2020-12-12 14:43 UTC, pouleyKetchoupp commented
Thanks for your tests and feedback!

In general, I'm planning to add box fields when you run the tests so you can change parameters easily. Maybe that will make all the different options and use cases clearer.

2020-12-14 16:24 UTC, pouleyKetchoupp commented
@aaronfranke Just pushed changes from your review.

2020-12-14 22:04 UTC, aaronfranke commented
Is there a reason that "Broadphase" is not in the menu?

2020-12-15 00:29 UTC, pouleyKetchoupp commented
> Is there a reason that "Broadphase" is not in the menu?

No, I forgot to add it. Thanks for catching this! It's fixed now.

2020-12-15 00:40 UTC, aaronfranke approved these changes

2020-12-15 01:36 UTC, merged