Add 2D Physics Tests
godotengine/godot-demo-projects pull request #560
Opened 2020-12-12 00:24 UTC by pouleyKetchoupp

Similar to its 3D counterpart, with tests using 2D physics.

![screenshot](https://user-images.githubusercontent.com/1075032/101966446-2609f300-3c18-11eb-9747-05a8a8ded8a1.png)

2020-12-12 02:31 UTC, pouleyKetchoupp commented
Added new test (Performance / Broadphase).

2020-12-12 10:33 UTC, aaronfranke requested changes
You accidentally left an empty `3d/physics_tests/tests/functional/test_raycasting.gd` file in this PR, which doesn't belong here (it's for 3D).

2020-12-12 10:33 UTC, aaronfranke commented on 2d/physics_tests/project.godot
> +environment/default_clear_color=Color( 0, 0, 0, 1 )
I think the clear color should be consistent between the 2D and 3D physics tests.

2020-12-12 10:33 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_raycasting.gd
> +	# draw raycast line.
```suggestion
	# Draw raycast line.
```

2020-12-12 10:33 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_raycasting.gd
> +	# draw raycast arrow.
```suggestion
	# Draw raycast arrow.
```

2020-12-12 10:33 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_raycasting.gd
> +		color = Color.gray.darkened(0.6)
I like how the arrows are colored red and green in the 3D demo, I think it would look good here too. Either way, the colors should probably be consistent between 2D and 3D physics tests.

2020-12-12 14:45 UTC, pouleyKetchoupp commented on 2d/physics_tests/tests/functional/test_raycasting.gd
> +		color = Color.gray.darkened(0.6)
I've tried to pick colors that contrast well with the physics render debug colors and they are not the same for 3D and 2D. I'll see how much I can harmonize it while keeping it readable for both.

2020-12-12 14:54 UTC, pouleyKetchoupp commented on 2d/physics_tests/tests/test_options.tscn
> +[gd_scene load_steps=2 format=2]
It's a little helper to avoid setting the correct margins, position and other parameters manually when I need this control.

What is the reason behind not allowing a scene with just one node? I personally use that all the time because it's much more practical and flexible than copying the same node between scenes, and I can't see a reason why we should tell users not to do it if it can save production time.

2020-12-12 17:02 UTC, aaronfranke commented on 2d/physics_tests/tests/test_options.tscn
> +[gd_scene load_steps=2 format=2]
Well, there's also the fact that this scene is only instanced in one place... so "when I need this control" is just once, in `test_perf_contacts.tscn`. Should we make every node its own scene? :upside_down_face: 

> What is the reason behind not allowing a scene with just one node?

To avoid making the demos more complicated than they need to be.

2020-12-13 15:28 UTC, pouleyKetchoupp commented on 2d/physics_tests/tests/test_options.tscn
> +[gd_scene load_steps=2 format=2]
We're only talking about a specific case, there's no need to be snarky here.

I'm going to use this node again for more scenes, so in this case I need to have it saved as a separate scene.

2020-12-13 17:13 UTC, aaronfranke commented on 2d/physics_tests/tests/test_options.tscn
> +[gd_scene load_steps=2 format=2]
Yeah. If there is a specific reason for this, then it's fine.

2020-12-14 15:52 UTC, pouleyKetchoupp commented on 2d/physics_tests/tests/functional/test_raycasting.gd
> +		color = Color.gray.darkened(0.6)
In the end I've used the same colors as in 3D. It's not the best contrast in some cases (convex polygon debug draw is red) but it's still readable.

2020-12-14 15:52 UTC, pouleyKetchoupp commented
@aaronfranke Just pushed changes from your review.

2020-12-14 16:13 UTC, pouleyKetchoupp commented
I've added an option for box spacing in pyramid and stack tests from https://github.com/godotengine/godot-demo-projects/pull/559#discussion_r541590559 to make 3D and 2D consistent.

2020-12-15 02:04 UTC, aaronfranke commented
We should compress the screenshot using `oxipng`. I tried to fix this for you, but I don't have permission to push to `nekomatata/godot-demo-projects`. Here is the optimized file:

![screenshot](https://user-images.githubusercontent.com/1646875/102157478-92ba0300-3e4d-11eb-9a98-f51952b387c6.png)

2020-12-16 16:12 UTC, pouleyKetchoupp commented
Thanks! Image replaced.

2020-12-16 20:47 UTC, aaronfranke approved these changes

2020-12-17 04:11 UTC, merged