Created old school FPS demo project
godotengine/godot-demo-projects pull request #571
Opened 2021-01-04 10:58 UTC by superegosoft

We created a simple project to have an FPS (old school) reference demo for Godot newcomers since it all the other engine seem to provide a similar demo.
The code is well commented, let us know what you think about it.
![oldschool_fps_2](https://user-images.githubusercontent.com/76686474/103528305-a02a4200-4e7b-11eb-9e65-b9eafd1ef4f4.jpg)
![oldschool_fps_1](https://user-images.githubusercontent.com/76686474/103528308-a0c2d880-4e7b-11eb-9204-b69a7eb3c0ef.jpg)

2021-01-07 05:42 UTC, aaronfranke requested changes
I think this would be better as an asset you publish to the [Godot Asset Library](https://godotengine.org/asset-library/asset) rather than an official demo. I came to this conclusion after reviewing this, because this code generally uses old-school techniques manually instead of just using Godot's built-in features - this is neat, but not really suitable for an official demo. Aside from that, we already have two demos with first-person character controllers (Voxel demo and 3D IK demo), so even if this demo was perfectly following all of Godot's best practices, I'm not sure if it would be a good fit (this part is subjective though, and certainly up for discussion).

I did try to give you lots of feedback, hopefully this is helpful for whatever fate this project has. Two other things I didn't mention below is that you are missing a README.md file, and also images can be compressed with `oxipng`.

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/project.godot
> +back={
Movement input names should be prefixed with `move_` since that's what the other demos do. Ex: `move_back`. It would also be nice to bind other keys (the arrow keys are a good one, and we can support French ZQSD by binding Z as forward and Q as back), and controller inputs (just binding the movement and not the look is simple and works for hybrid devices, though joystick look should probably also be implemented for this project).

Also, there should be an input action for exiting the game (bind the escape key).

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_controller.gd
> +export(float) var player_height  = 4.0
Godot's units are meters by default, and the demos should reflect this. The player is too tall, and everything is too big. Average human height is 1.7 meters.

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_controller.gd
> +export(float) var gravity = 1.0
Godot already defines gravity, so we should use it:

```suggestion
onready var gravity = ProjectSettings.get_setting("physics/3d/default_gravity")
```

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_controller.gd
> +const RADIAN_RIGHT_ANGLE = 1.5708
```suggestion
```

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_controller.gd
> +				var ray_hit_result = space_state.intersect_ray(ray_origin, ray_origin + horizontal_velocity + player_radius * horizontal_velocity.normalized())
I get the idea of this (some kind of old-school technique?), but using Godot's physics bodies are a much better idea if this project were to be a Godot demo. Of course, you can use any technique you want in your own project.

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_controller.gd
> +# Called when the node enters the scene tree for the first time.
```suggestion
```

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_enemy.gd
> +# for this examples enemies simply move in a random direction until they die, then they are cycled out
For comments, they should start with a capital letter, have sentences ending with a period, and have line length not exceeding 80 characters in most situations.

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scenes/Player.tscn
> +
Empty lines in `tscn` files like this are caused by a Godot bug. You can fix it by opening the scene and saving again.

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_controller.gd
> +	if direction_input != Vector3(0, 0, 0):
If this is guaranteed to be a Vector3 of some kind, you can just do:

```suggestion
	if direction_input:
```

Otherwise, prefer this:

```suggestion
	if direction_input != Vector3.ZERO:
```

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_controller.gd
> +	mouse_delta = Vector2(0,0) # reset mouse delta after we're done with it, doesn't get reset if there is no mouse input
Not following the [style guide](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html), should be a space after the comma. But generally prefer `Vector2.ZERO`.

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_player_animator.gd
> +# Called when the node enters the scene tree for the first time.
```suggestion
```

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_enemy_manager.gd
> +# Called when the node enters the scene tree for the first time.
```suggestion
```

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_enemy.gd
> +					 0, rand_range(-ENEMY_SPEED_RANGE,ENEMY_SPEED_RANGE))
Per the [style guide](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html), there should be spaces after commas.

```suggestion
			velocity = Vector3(rand_range(-ENEMY_SPEED_RANGE, ENEMY_SPEED_RANGE),
					 0, rand_range(-ENEMY_SPEED_RANGE, ENEMY_SPEED_RANGE))
```

2021-01-07 05:42 UTC, aaronfranke commented on 3d/oldschool_fps/oldschool_fps/Scripts/fps_controller.gd
> +					horizontal_velocity = wall_direction * accel_speed * delta * velocity_modifier
If this code is kept for your uses, you can achieve this affect using [`Vector3.slide`](https://docs.godotengine.org/en/latest/classes/class_vector3.html#class-vector3-method-slide).

2021-01-07 19:05 UTC, Calinou commented
I also agree this would be better as a third-party demo on the asset library.

2021-01-07 21:35 UTC, JJRWalker commented
> I think this would be better as an asset you publish to the [Godot Asset Library](https://godotengine.org/asset-library/asset) rather than an official demo. I came to this conclusion after reviewing this, because this code generally uses old-school techniques manually instead of just using Godot's built-in features - this is neat, but not really suitable for an official demo. Aside from that, we already have two demos with first-person character controllers (Voxel demo and 3D IK demo), so even if this demo was perfectly following all of Godot's best practices, I'm not sure if it would be a good fit (this part is subjective though, and certainly up for discussion).
> 
> I did try to give you lots of feedback, hopefully this is helpful for whatever fate this project has. Two other things I didn't mention below are that you are missing a README.md file, and also images can be compressed with `oxipng`.

Thanks for the feedback! I appreciate it! I was wondering are there alterations that could be made to make this something worthwhile to have as a demo? Although don't worry if there isn't, I don't expect there would be as you've made some good points as to why not 😅

2021-01-15 08:42 UTC, aaronfranke commented
I'm closing this. Feel free to submit this to the Godot Asset Library (but I recommend going over the above feedback first).

2021-01-15 08:42 UTC, closed without merging