Add One Way Collision for 2D Physics tests
godotengine/godot-demo-projects pull request #573
Opened 2021-01-04 16:35 UTC by pouleyKetchoupp

Update 2D Physics tests with a new demo to test one way collision.

This test scene is inspired by the "Around the Clock" test made by @madmiraal in https://github.com/madmiraal/godot-gym in order to test this PR: https://github.com/godotengine/godot/issues/42916

Like the original test, it allows testing collision between a rigid/kinematic body object and a one-way collision platform at different angles.

This new version is a bit different to be able to use it in a more practical way within the physics test framework:
- There are options and sliders to set different test cases (kinematic or rigid body, platform size, etc.)
- You can still test all angles around the clock, but you can also test only one particular case for debug purpose
- When all angles have been tested, the log gives you information about which sets of parameters have failed
- Only the platform rotates for "around the clock" test and the rigid body goes horizontally to avoid redundant cases

Overall, the idea is to be able to test a set of parameters in less than a minute, check the log for failed cases and test these failed cases easily.

@madmiraal I think it covers the same cases as your original test, but if you have some time to have a look, please let me know in case I overlooked something.

2021-01-06 04:40 UTC, aaronfranke requested changes

2021-01-06 04:40 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_one_way_collision.gd
> +export(float, 0, 360, 0.1) var _rigidbody_angle = 0 setget _set_rigidbody_angle
These are exported as floats, but the inspector infers their type as int unless you add a trailing `.0`.

```suggestion
export(float, 32, 128, 0.1) var _platform_size = 64.0 setget _set_platform_size
export(float, 0, 360, 0.1) var _platform_angle = 0.0 setget _set_platform_angle
export(float, 0, 360, 0.1) var _rigidbody_angle = 0.0 setget _set_rigidbody_angle
```

2021-01-06 04:40 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_one_way_collision.gd
> +
We have a method for this :)

```suggestion
	var angle = fposmod(platform_rotation, 360)
```

2021-01-06 04:40 UTC, aaronfranke commented on 2d/physics_tests/utils/slider.gd
> +		step = 0.1
Maybe it should be the other way around, to make the special cases like 180 degrees easily accessible? Also. `has_focus()` doesn't seem to be necessary to get the correct behavior.

```suggestion
	if Input.is_key_pressed(KEY_SHIFT):
		step = 0.1
	else:
		step = snap_step
```

2021-01-06 04:40 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_one_way_collision.tscn
> +step = 0.1
```suggestion
```

2021-01-06 04:40 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_one_way_collision.tscn
> +step = 0.1
```suggestion
```

2021-01-06 04:40 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_one_way_collision.tscn
> +step = 0.1
```suggestion
```

2021-01-06 04:40 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_one_way_collision.gd
> +	if _rigidbody && _use_kinematic_body:
Old habits die hard :)

```suggestion
	if _rigidbody and _use_kinematic_body:
```

2021-01-06 04:40 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_one_way_collision.gd
> +	if _test_all_angles:
It would be nice to update the slider during the test, but I tried doing this myself and it just caused the test to terminate prematurely.

2021-01-07 00:14 UTC, pouleyKetchoupp commented
Thanks @aaronfranke! I've updated the test from all your suggestions.

2021-01-07 02:03 UTC, pouleyKetchoupp commented
I've just added proper support for `KinematicBody2D`, and key shortcuts.

2021-01-07 02:44 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_one_way_collision.tscn
> +_use_kinematic_body = true
Is this intentional? It's fine either way, but it seems strange that the second option is the default one.

2021-01-07 03:25 UTC, pouleyKetchoupp commented on 2d/physics_tests/tests/functional/test_one_way_collision.tscn
> +_use_kinematic_body = true
Ah no it's not, I forgot to revert the change before pushing :)

2021-01-07 03:39 UTC, aaronfranke approved these changes

2021-01-07 04:00 UTC, merged