[Joypads] Add SDL config re-mapping tool.
godotengine/godot-demo-projects pull request #575
Opened 2021-01-18 11:39 UTC by Faless

Most of the code is in the remap folder, but it depends on the gamepad
diagram scene.
It allows remapping of pads to values that godot can understand.
It also comes with some default mapping for the HTML5 platform.

See godotengine/godot#45078

![remap](https://user-images.githubusercontent.com/1687918/104910749-12c21400-598a-11eb-8e94-a0bd9f7b4c28.png)

2021-01-20 08:42 UTC, aaronfranke requested changes
Please ensure that PRs don't have warnings and follow all style guides.

2021-01-20 08:42 UTC, aaronfranke commented on misc/joypads/remap/remap_wizard.gd
> +			var key = steps[cur_step]
```
W 0:00:01.183   The local variable 'key' is declared but never used in the block. If this is intended, prefix it with an underscore: '_key'
  <C++ Error>   UNUSED_VARIABLE
  <Source>      remap_wizard.gd:107
```

2021-01-20 08:42 UTC, aaronfranke commented on misc/joypads/remap/joy_mapping.gd
> +func _init(type = TYPE.NONE, idx = -1, axis = AXIS.FULL):
```
W 0:00:01.306   The local variable 'type' is shadowing an already-defined variable at line 80.
  <C++ Error>   SHADOWED_VARIABLE
  <Source>      joy_mapping.gd:85
W 0:00:01.306   The local variable 'idx' is shadowing an already-defined variable at line 81.
  <C++ Error>   SHADOWED_VARIABLE
  <Source>      joy_mapping.gd:85
W 0:00:01.306   The local variable 'axis' is shadowing an already-defined variable at line 82.
  <C++ Error>   SHADOWED_VARIABLE
  <Source>      joy_mapping.gd:85
```

In this case, we can just do this:

```suggestion
# warning-ignore-all:shadowed_variable
func _init(type = TYPE.NONE, idx = -1, axis = AXIS.FULL):
```

2021-01-20 08:42 UTC, aaronfranke commented on misc/joypads/remap/joy_mapping.gd
> +func _to_string():
Per the [GDScript style guide](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html), there needs to be two lines between methods.

```suggestion


func _to_string():
```

2021-01-20 08:42 UTC, aaronfranke commented on misc/joypads/remap/remap_wizard.gd
> +		# Propose trying known mapping on HTML5
```suggestion
		# Propose trying known mapping on HTML5.
```

2021-01-20 22:30 UTC, aaronfranke requested changes
It doesn't work correctly in my testing, tested with both 3.2.3 and 3.2.4 beta 6. I tried remapping a Stadia controller on Windows. Firstly, I can't map the A button unless I click on a UI element to change the focused button, because the A button immediately closes the wizard (this needs to be fixed, you can probably just focus some other UI element to prevent this). Anyway, I clicked elsewhere and mapped it and this is what I got on 3.2.3:

    03000000d11800000094000000000000,Stadia Controller,a:b0,b:b1,y:b3,x:b2,start:b9,back:b8,leftstick:b6,rightstick:b7,leftshoulder:b4,rightshoulder:b5,dpup:b12,dpleft:b14,dpdown:b13,dpright:b15,leftx:a0,lefty:a2,rightx:a3,righty:a5,lefttrigger:b12,righttrigger:b11,platform:Javascript

There are several problems with this. For one, why does it say "platform:Javascript" when this is Windows? For another, the triggers don't seem to map correctly. What was *really* confusing is that **"Clear Mapping" doesn't actually set it to the default mapping,** and clicking "Clear Mapping messes up the whole mapping (while the default mapping when starting the program is correct).

For the left trigger, the default mapping has it as Button 6 (interpreted as left trigger), and Steam detects it as Button 12 (interpreted as left trigger), and the remapper detects it as Button 12 (interpreted as D-pad up), then clicking "Clear Mapping" sets it to Button 12 (interpreted as D-pad up).

For the right trigger, the default mapping has it as Button 7 (interpreted as right trigger), and Steam detects it as Button 11 (interpreted as right trigger), and the remapper detects it as Button 7 (interpreted as left trigger), then clicking "Clear Mapping" sets it to Button 11 (interpreted as the Start button).

For the D-pad, Godot detects it as buttons 12-15, but Steam detects it as "Hat 0.1" for up, "Hat 0.8" for left, "Hat 0.4" for down, and "Hat 0.2" for right. The remapper works for the D-pad, but this behavior seems strange.

When clicking "Clear Mapping", the triggers are interpreted as D-pad up and Start, and Select/Start are interpreted as the joystick clicks, and the joystick clicks are interpreted as the triggers. Nothing maps to select, two things map to D-pad up.

Then I tried on 3.2.4 beta 6 and I got the exact same behavior, same map string, same bad behavior, same broken "Clear Mapping" button.

There is also the popup with "Try a common mapping" that I can see in the Godot editor, it doesn't show up when clicking any of the buttons on the bottom (Remap starts the wizard immediately, Show brings up text, and Clear Mapping doesn't open anything), so it seems that this menu is impossible to get to (and should either become accessible, or deleted).

2021-01-21 14:15 UTC, Faless commented
> I can't map the A button unless I click on a UI element to change the focused button

That is indeed a bug, we need to ignore the gamepad UI actions, I did that in my test project but forgot about it.
I will try to find a workaround for it.

> What was _really_ confusing is that **"Clear Mapping" doesn't actually set it to the default mapping,** and clicking "Clear Mapping" messes up the whole mapping (while the default mapping when starting the program is correct).

As far as I understand resetting to the godot builtin mapping is not possible via scripting API, "clear mapping" removes the current mapping, and shows "raw" inputs.

> For the D-pad, Godot detects it as buttons 12-15, but Steam detects it as "Hat 0.1" for up, "Hat 0.8" for left, "Hat 0.4" for down, and "Hat 0.2" for right. The remapper works for the D-pad, but this behavior seems strange.

Godot exposes Hats as buttons. So, there isn't much we can do about it.

> There is also the popup with "Try a common mapping" that I can see in the Godot editor, it doesn't show up when clicking any of the buttons on the bottom (Remap starts the wizard immediately, Show brings up text, and Clear Mapping doesn't open anything), so it seems that this menu is impossible to get to (and should either become accessible, or deleted).

That's only for platforms that have known mappings (for now, HTML5 only).

2021-02-04 14:37 UTC, Faless commented
@aaronfranke 
Thanks a lot for the review.
I've fixed both the issue with the platform name, and the one about input not being properly consumed.

2021-02-07 06:11 UTC, aaronfranke requested changes
Now this is what I get when mapping a Stadia controller on Windows:

    03000000d11800000094000000000000,Stadia Controller,a:b0,b:b1,y:b3,x:b2,start:b9,back:b8,leftstick:b6,rightstick:b7,leftshoulder:b4,rightshoulder:b5,dpup:b12,dpleft:b14,dpdown:b13,dpright:b15,leftx:a0,lefty:a2,rightx:a3,righty:a5,lefttrigger:b12,righttrigger:b11,platform:Windows

I am able to map all inputs without the menu closing when pressing A, and the platform is reported correctly. Using the remapper tool, the only button bound incorrectly is the left trigger which is detected as D-pad up. In my last comment I reported that the right trigger was bound incorrectly, but it seems to be working now.

> As far as I understand resetting to the godot builtin mapping is not possible via scripting API, "clear mapping" removes the current mapping, and shows "raw" inputs.

I see, but we still need to make it clear what's happening, since "Clear Mapping" does not convey this. What about "Raw Mapping", "Set to Raw Mapping", or "Set to Raw"?

2021-02-07 06:11 UTC, aaronfranke commented on misc/joypads/remap/remap_wizard.tscn
> +[node name="buttons" type="HBoxContainer" parent="Start/Layout"]
Node names should be in PascalCase, so this one should be `Buttons`, not `buttons`.

I'm not sure if you have a specific reason for `html5` and `xbox` to be lowercase, if not please change them too.

2021-02-07 06:11 UTC, aaronfranke commented on misc/joypads/remap/remap_wizard.gd
> +var last_mapping = ""
Per [the style guide's code order section](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html#code-order), `onready var`s go below non-onready `var`s to be closer to the lifecycle methods (which aren't present in this script, but the rule still applies).

2021-02-07 06:11 UTC, aaronfranke commented on misc/joypads/remap/remap_wizard.gd
> +func _input(event):
Per [the style guide's code order section](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html#code-order), built-in virtual methods go above others, so `_input` should go on top. The rest of the methods are in a good order.

2021-02-07 06:16 UTC, aaronfranke requested changes

2021-02-07 06:16 UTC, aaronfranke commented on misc/joypads/remap/remap_wizard.gd
> +func show_map():
```suggestion
		_update_step()


func show_map():
```

2021-02-07 06:16 UTC, aaronfranke commented on misc/joypads/remap/remap_wizard.gd
> +	$Mapping.window_title = "Step: %d/%d" % [cur_step+1, steps.size()]
```suggestion
	$Mapping.window_title = "Step: %d/%d" % [cur_step + 1, steps.size()]
```

2021-02-07 06:16 UTC, aaronfranke commented on misc/joypads/remap/remap_wizard.gd
> +	if OS.get_name() == 'HTML5':
```suggestion
	if OS.get_name() == "HTML5":
```

2021-02-07 12:22 UTC, Faless commented
Okay, I think I addressed all the remaining issues.

2021-02-07 18:59 UTC, aaronfranke approved these changes
Looks good to me.

2021-02-07 21:24 UTC, merged