Deploy exported HTML5 demos to GitHub Pages
godotengine/godot-demo-projects pull request #582
Opened 2021-02-22 01:54 UTC by Calinou

This makes it possible for users to test Godot's features without having to download anything.

Several other game engines such as Urho3D already provide pre-exported HTML5 demos. This puts Godot on the same foothold :slightly_smiling_face:

2021-02-22 02:13 UTC, aaronfranke commented on .github/workflows/continuous_integration.yml
> +name: Continuous integration
This line, and the file name, should probably be given more descriptive names.

How come I don't see this CI workflow running [on your repo](https://github.com/Calinou/godot-demo-projects/runs/1948505163)?

2021-02-22 02:13 UTC, aaronfranke commented on .github/workflows/continuous_integration.yml
> +          rm -rf mono/ networking plugins/
```suggestion
          rm -rf mono/ networking/ plugins/
```

2021-02-22 02:14 UTC, Calinou commented on .github/workflows/continuous_integration.yml
> +name: Continuous integration
> How come I don't see this CI workflow running on your repo?

I added `branches: master` at the top, since we want it to run only on the `master` branch upstream. However, to test this on a fork, you need to comment out that part so that your non-`master` branch can still be deployed to your fork's GitHub Pages space.

2021-02-22 02:36 UTC, aaronfranke commented
`2d/hdr/` should be excluded, this effect doesn't work with GLES 2.

`audio/device_changer/` should be excluded, it's completely useless in a web browser.

`loading/background_load/`, `loading/multiple_threads_loading/`, and `loading/threads/` seem to be broken, exclude?

`misc/matrix_transform/` should be excluded, it's a playground for the editor, and has no content when run as a game.

`mobile/android_iap/` should be excluded, it doesn't work on a non-Android export.

`mobile/sensors/` should probably be excluded, it doesn't seem to work via a web browser on a mobile device.

`3d/voxel/` seems to be broken, everything is invisible for me on both Chrome and Firefox.

2021-02-27 22:01 UTC, Calinou commented
I excluded some demos per @aaronfranke's comment and improved the visual presentation of the page.

2021-02-28 02:33 UTC, aaronfranke requested changes
What is `.nojekyll` for?

2021-02-28 02:33 UTC, aaronfranke commented on .github/workflows/export_html5.yml
> +    #   - master
Is it intentional for these to be commented out?

2021-02-28 02:33 UTC, aaronfranke commented on mono/2.5d/project.godot
> -
This diff should be reverted, it's caused by opening in 3.2.4. Open in 3.2.3 to fix it.

2021-02-28 02:33 UTC, aaronfranke commented on .github/dist/header.html
> +    <meta charset="utf-8">
I think we should use tabs in these files, it's a lower file size.

2021-02-28 02:34 UTC, Calinou commented on .github/workflows/export_html5.yml
> +    #   - master
No, I commented this for testing but it should be uncommented again before merging.

2021-02-28 02:34 UTC, Calinou commented
> What is `.nojekyll` for?

The `.nojekyll` file makes GitHub Pages not try to use Jekyll to build the website files.

2021-02-28 02:55 UTC, aaronfranke reviewed
We should also link to the website from the README file.

2021-02-28 02:55 UTC, aaronfranke commented on .github/workflows/export_html5.yml
> +            echo "<li><a href='$demo'><img width="64" height="64" src="$demo/favicon.png" alt=""> $demo</a></li>" >> "$BASEDIR/.github/dist/demos.html"
It would be nice to have the name on the website be the name of the project. Untested on GitHub Actions, but I think this will work:

```suggestion
            PROJECT_NAME=$(cat project.godot | grep "config/name" | tail -c -14 | head -c -2)

            # Append the demo to the list of demos for the website.
            echo "<li><a href='$demo'><img width="64" height="64" src="$demo/favicon.png" alt=""> $PROJECT_NAME</a></li>" >> "$BASEDIR/.github/dist/demos.html"
```

2021-02-28 03:16 UTC, aaronfranke commented on .github/workflows/export_html5.yml
> +            echo "<li><a href='$demo'><img width="64" height="64" src="$demo/favicon.png" alt=""> $PROJECT_NAME</a></li>" >> "$BASEDIR/.github/dist/demos.html"
There is an extra line added that you missed: `PROJECT_NAME=$(cat project.godot | grep "config/name" | tail -c -14 | head -c -2)`

```suggestion
            PROJECT_NAME=$(cat project.godot | grep "config/name" | tail -c -14 | head -c -2)

            # Append the demo to the list of demos for the website.
            echo "<li><a href='$demo'><img width="64" height="64" src="$demo/favicon.png" alt=""> $PROJECT_NAME</a></li>" >> "$BASEDIR/.github/dist/demos.html"
```

2021-02-28 03:37 UTC, aaronfranke requested changes

2021-02-28 03:37 UTC, aaronfranke commented on .github/workflows/export_html5.yml
> +            PROJECT_NAME=$(cat project.godot | grep "config/name" | tail -c -14 | head -c -2)
Shoot, tail doesn't actually work as expected, `cut` seems to work:

```suggestion
            PROJECT_NAME=$(cat project.godot | grep "config/name" | cut -c 14- | head -c -2)
```

2021-02-28 03:39 UTC, Calinou commented on .github/workflows/export_html5.yml
> +            PROJECT_NAME=$(cat project.godot | grep "config/name" | tail -c -14 | head -c -2)
I found a different solution, let's see if it works.

2021-02-28 03:40 UTC, aaronfranke commented on .github/workflows/export_html5.yml
> +            PROJECT_NAME=$(cat project.godot | grep "config/name" | tail -c -14 | head -c -2)
It looks like you forgot to add the changes before committing.

2021-02-28 04:15 UTC, aaronfranke approved these changes

2021-02-28 04:16 UTC, aaronfranke commented
Looks good, let's merge and see if it works on the main repo :)

2021-02-28 04:16 UTC, merged