Updated 2D character controller physics tests
godotengine/godot-demo-projects pull request #584
Opened 2021-02-23 02:26 UTC by pouleyKetchoupp

Added new test for 2D character controller:
Character - Pixels
Functional test for pixel art related issues around KinematicBody and RigidBody character controllers.

Adjusted existing tests and added more test cases to cover most use cases from recent fixed issues and regressions for KinematicBody.

Added a more automated way to run all tests with checks to see which ones failed in character controller tests.

Also fixed some minor issues with the log scrollbar.

2021-02-23 02:42 UTC, aaronfranke requested changes

2021-02-23 02:42 UTC, aaronfranke commented on 2d/physics_tests/tests/functional/test_one_way_collision.gd
> +		$Options.add_menu_item(OPTION_TEST_CASE_MOVING_PLATFORM_KINEMATIC)
Instead of doing this, we should have `onready var options = $Options` and then reference it everywhere. This should also be done for the other files. We want to avoid the inefficiency of getting a node more times than necessary.

2021-02-23 03:02 UTC, pouleyKetchoupp commented on 2d/physics_tests/tests/functional/test_one_way_collision.gd
> +		$Options.add_menu_item(OPTION_TEST_CASE_MOVING_PLATFORM_KINEMATIC)
It's true, even if it's not critical here it's not good practice. I'll change it in the different files. Thanks!

2021-02-26 14:10 UTC, aaronfranke approved these changes
Forgot to give this an approval earlier, looks good!

2021-02-26 14:25 UTC, merged