Added interpolation functionality
godotengine/godot-demo-projects pull request #585
Opened 2021-02-25 04:27 UTC by ThomasFederau

a slider with a range of 0 - 1 will now appear in the editor. Control of the bone is interpolated between the original bone rotation and the IK lookat rotation.

2021-02-26 15:24 UTC, aaronfranke requested changes
I'm not really sure why this is useful, but since the SkeletonIK node has this feature, it makes sense for this script to have it too. But please make the requested change below (and if you can, rebase and squash).

2021-02-26 15:24 UTC, aaronfranke commented on 3d/ik/addons/sade/ik_look_at.gd
> +export(float, 0,1,0.001) var interpolation = 1;
```suggestion
export(float, 0.0, 1.0, 0.001) var interpolation = 1.0;
```

2021-02-26 20:05 UTC, ThomasFederau commented on 3d/ik/addons/sade/ik_look_at.gd
> +export(float, 0,1,0.001) var interpolation = 1;
Sounds good, I'll do that once I get home from work. The reason I made this change is because I found it useful in my project, and I figured that I might as well share it. My characters head is controlled by animation normally, but I want him to look in the direction of objects of interest whenever there is one nearby, or whenever I am "z targetting". Interpolation gives me an easy way to switcg between animation controlled head movement, and ik controlled movement.

2021-02-27 03:23 UTC, aaronfranke requested changes

2021-02-27 03:23 UTC, aaronfranke commented on 3d/ik/addons/sade/ik_look_at.gd
> +export(float, 0.0, 1.0, 0.001) var interpolation = 1.0;
Sorry, I missed this earlier... one more thing, no semicolons:

```suggestion
export(float, 0.0, 1.0, 0.001) var interpolation = 1.0
```

2021-02-27 03:29 UTC, aaronfranke approved these changes

2021-02-27 03:29 UTC, merged