Fix MIDI devices scanning
godotengine/godot-demo-projects pull request #604
Opened 2021-04-05 18:24 UTC by waimus

Fixes #603.

Calls `OS.open_midi_inputs()` before `OS.get_connected_midi_inputs()` and then close MIDI inputs.

2021-04-05 18:26 UTC, aaronfranke requested changes
Functions should be surrounded by 2 blank lines.

2021-04-05 18:40 UTC, aaronfranke approved these changes
Code looks good. These commits should be squashed into one. Either you can do it, or I can use GitHub's squash-and-merge feature (not as nice since it doesn't preserve history).

2021-04-05 18:58 UTC, waimus commented
Okay I've just heard the term "squash" as of now, as this is my first PR as well :D I'm not too sure what that means, I thought it was to "merge".

Can I follow [this](https://gist.github.com/patik/b8a9dc5cd356f9f6f980) on my fork to do that?

2021-04-05 19:49 UTC, Calinou commented
@waimus We have a guide on rebasing here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

2021-04-05 20:14 UTC, waimus commented
@Calinou Thank you, I successfully squashed the commits.

2021-04-05 20:50 UTC, aaronfranke approved these changes

2021-04-05 20:51 UTC, merged

2021-04-24 09:51 UTC, aaronfranke commented
This crashes in Godot 3.3 (at least on my Linux system). I've [temporarily removed it](https://github.com/godotengine/godot-demo-projects/commit/31bb09233b32da56d2e7cbcab9f8be1b0c82898a#diff-f8ada95751429d5cdc00716e677f2a4e7ce47a9559b2c43c1f6094ad9cfd27e8L68) in the master branch for the 3.3 release, but perhaps you can investigate why this crashes in Godot 3.3 and submit a PR?

2021-04-24 10:04 UTC, waimus commented
Not sure how far I can investigate. But so far I found that the crash caused by `OS.open_midi_inputs()`. It also occurs when creating a new project with Godot 3.3.

2021-04-24 10:12 UTC, waimus commented
It prints this log
```
Running: /home/waimus/.steam/debian-installation/steamapps/common/Godot Engine/godot.x11.opt.tools.64 --path /home/waimus/Documents/godot-projects/midi_test --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 11901 --position 171,84
Godot Engine v3.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce 920M/PCIe/SSE2
OpenGL ES Batching: ON
 
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7fe672508950] (??:0)
-- END OF BACKTRACE --

```