Additional 3D physics tests - RigidBody impact and ground check
godotengine/godot-demo-projects pull request #619
Opened 2021-05-21 09:34 UTC by nezvers

RigidBody impact allows observing a hit through when RigidBody collides with the floor.

Rigidbody ground check allows testing how reliable is sliding against the floor. At the moment the only way to check if RigidBody is on the floor is through get_world().direct_space_state.get_rest_info(). In the test when the body is not on the floor its mesh is in red color.
P.S. GodotPhysics have a more stable connection to the floor.

2021-05-24 17:50 UTC, pouleyKetchoupp requested changes
Thanks for adding more test cases! It looks great overall. I've commented on some details, mostly coding style changes.

The ground check could be used to test both rigid bodies and kinematic bodies, but this can be updated later.

Just one thing that could be improved:
Currently rigid body picking is not working very well in the impact test, because the camera has a different fov and the mouse follow code doesn't handle that.

Could you please update this line:
https://github.com/godotengine/godot-demo-projects/blob/e0db0b8f6df989a7dcfa5572feac9df3194fa825/3d/physics_tests/utils/rigidbody_pick.gd#L50

With:
```
var fov_coefficient = camera.fov / 70.0
world_delta *= CAMERA_DISTANCE_COEFFICIENT * camera_dist * fov_coefficient
```

2021-05-24 17:50 UTC, pouleyKetchoupp commented on 3d/physics_tests/tests.gd
> +		"id": "Functional Tests/RiggidBody impact",
```suggestion
		"id": "Functional Tests/RigidBody impact",
```

2021-05-24 17:50 UTC, pouleyKetchoupp commented on 3d/physics_tests/tests.gd
> +		"id": "Functional Tests/RiggidBody ground check",
```suggestion
		"id": "Functional Tests/RigidBody ground check",
```

2021-05-24 17:50 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +var _is_on_floor:bool = false
The current rule for demos is "no static typing unless it significantly improves readability" so it's probably not needed for all these variables.

There are also more in function arguments, local variables and return values that can be removed.

2021-05-24 17:50 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +
Demos need to follow GDScript coding style, so it needs two blank lines after the header, and two blank lines before each function.

Reference: https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html

2021-05-24 17:50 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +func _integrate_forces(state:PhysicsDirectBodyState):
The order of functions should be first _process, then _integrate_forces, then _ground_check (with _ prefix because it's private).

2021-05-25 13:16 UTC, nezvers commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +var _is_on_floor:bool = false
By static typing you mean only type name?

2021-05-25 16:18 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +var _is_on_floor:bool = false
Yes, I mean writing type names:
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/static_typing.html

2021-05-25 20:54 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +
It's still missing two blank lines here and in-between each function. Otherwise it's all fine now!

2021-05-25 20:56 UTC, aaronfranke commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +	var velocity = (_forward *_dir *_walk_spd *delta) +(state.linear_velocity  *Vector3(0,1,0))
The spacing around these operators is not correct.

2021-05-26 17:32 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +
Just one last blank line missing right here, there should be two before the function :)

2021-05-26 17:33 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +	var velocity = (_forward * _dir * _walk_spd * delta) + (state.linear_velocity  * Vector3(0,1,0))
One last thing to fix: `Vector3(0, 1, 0)` instead of `Vector3(0,1,0)`.

Whitespace rules are here for info:
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#whitespace

2021-05-26 18:07 UTC, aaronfranke commented on 3d/physics_tests/utils/rigidbody_ground_check.gd
> +	var velocity = (_forward * _dir * _walk_spd * delta) + (state.linear_velocity  * Vector3(0,1,0))
Could also just be `Vector3.UP`.

2021-05-28 18:24 UTC, nezvers commented
> Thanks for adding more test cases! It looks great overall. I've commented on some details, mostly coding style changes.
> 
> The ground check could be used to test both rigid bodies and kinematic bodies, but this can be updated later.
> 
> Just one thing that could be improved:
> Currently rigid body picking is not working very well in the impact test, because the camera has a different fov and the mouse follow code doesn't handle that.
> 
> Could you please update this line:
> https://github.com/godotengine/godot-demo-projects/blob/e0db0b8f6df989a7dcfa5572feac9df3194fa825/3d/physics_tests/utils/rigidbody_pick.gd#L50
> 
> With:
> 
> ```
> var fov_coefficient = camera.fov / 70.0
> world_delta *= CAMERA_DISTANCE_COEFFICIENT * camera_dist * fov_coefficient
> ```

This was fixed but is still shown as a requested change.

2021-05-28 18:32 UTC, pouleyKetchoupp commented
> This was fixed but is still shown as a requested change.

This camera change is fine, but I haven't approved the PR yet because there's still one last gdscript style change to make:

> Just one last blank line missing right here, there should be two before the function :)

And there's also a possible simplification to make from @aaronfranke's comment:

> Could also just be Vector3.UP.

2021-05-28 22:47 UTC, pouleyKetchoupp approved these changes
Perfect, thank you!

2021-05-29 06:54 UTC, aaronfranke approved these changes

2021-05-29 06:58 UTC, merged