3D physics tests - Moving platform
godotengine/godot-demo-projects pull request #623
Opened 2021-05-30 21:20 UTC by nezvers

Manually and visually testable variations of the KinematicBody platform with KinematicBody & RigidBody characters on it.
The test options menu has visually persistent toggles - doesn't hide options between active character body types.

2021-06-02 00:15 UTC, pouleyKetchoupp requested changes
Looks great! I've just commented on style changes and possibly an option to remove.

2021-06-02 00:15 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/kinematicbody_physics.gd
> +		_velocity += get_floor_velocity()
I'm not sure this option is really useful for regression tests, since the floor velocity is supposed to be applied within `move_and_slide` (it seems there's a bug with Bullet though and it's not applied correctly).

2021-06-02 00:15 UTC, pouleyKetchoupp commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +
This should be double blank line.

2021-06-02 00:15 UTC, pouleyKetchoupp commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +		if _index >= 0 && _index < _key_list.size():
No `&&` or `||` (gdscript style guide)
```suggestion
		if _index >= 0 and _index < _key_list.size():
```

2021-06-02 00:15 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/kinematicbody_physics.gd
> +	if is_on_floor() && _gravity_on_floor:
Same here.
```suggestion
	if is_on_floor() and _gravity_on_floor:
```

2021-06-02 00:15 UTC, pouleyKetchoupp commented on 3d/physics_tests/utils/kinematicbody_physics.gd
> +export (bool) var _use_floor_velocity = false
The usual style is `export(bool) var` (without a space) but I'm not sure if it's a strict rule.

2021-06-02 06:57 UTC, nezvers commented on 3d/physics_tests/utils/kinematicbody_physics.gd
> +		_velocity += get_floor_velocity()
get_floor_velocity is applied to velocity which is used in move_and_slide / move_and_slide_with_snap.
Or I'm misunderstanding something.
Also, the value received from get_floor_velocity varies depending on FPS at least with AnimationPlayer process mode Idle.

2021-06-02 07:10 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +
done

2021-06-02 07:10 UTC, nezvers commented on 3d/physics_tests/utils/kinematicbody_physics.gd
> +export (bool) var _use_floor_velocity = false
done

2021-06-07 12:28 UTC, aaronfranke requested changes
When I start the Moving Platform test, it just makes a platform that doesn't move and there is nothing on it. I have to press 1 or 2, or set the body type in the menu, to make the test run. It should be changed so that starting the test automatically selects one option (probably KinematicBody).

2021-06-07 12:28 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +	var bodyParent = $Bodies
Should be `var body_parent`

2021-06-07 12:28 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +	var animationPlayer = $Platforms/KinematicPlatform/AnimationPlayer
Should be `var animation_player`

2021-06-07 12:28 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +	var packedScene = PackedScene.new()
Should be `var packed_scene`

2021-06-07 12:31 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +	animationPlayer.playback_process_mode = AnimationPlayer.ANIMATION_PROCESS_PHYSICS if _animation_physics else AnimationPlayer.ANIMATION_PROCESS_IDLE
This ternary operator is too long, replace it with:

```suggestion
	if _animation_physics:
		animation_player.playback_process_mode = AnimationPlayer.ANIMATION_PROCESS_PHYSICS
	else:
		animation_player.playback_process_mode = AnimationPlayer.ANIMATION_PROCESS_IDLE
```

2021-06-08 21:01 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +	var bodyParent = $Bodies
done

2021-06-08 21:01 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +	var packedScene = PackedScene.new()
done

2021-06-09 00:23 UTC, aaronfranke requested changes

2021-06-09 00:23 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +func spawn_body_index(bodyIndex):
Should be `body_index`

2021-06-09 00:23 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +func spawn_body_key(bodyKey):
Should be `body_key`

2021-06-09 00:23 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +	var body = _body_scene[ _key_list[bodyIndex] ].instance()
Unnecessary/undesired spaces in the brackets.

2021-06-09 05:50 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +func spawn_body_index(bodyIndex):
done

2021-06-09 05:50 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +func spawn_body_key(bodyKey):
done

2021-06-09 05:50 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +	var body = _body_scene[ _key_list[bodyIndex] ].instance()
done

2021-06-09 12:26 UTC, aaronfranke approved these changes
Looks good! Can use a squash.

Note that GitHub does have a squash-and-merge feature, so if you don't squash yourself then I can squash for you, but if you squash it yourself then when I merge I will preserve that Git history.

2021-06-10 00:57 UTC, merged