Update impact, rigid groundcheck, moving platform
godotengine/godot-demo-projects pull request #634
Opened 2021-07-08 05:47 UTC by nezvers

Added Ray collision shape to these tests.
RigidBody ground check has added floor segment with convex shape, previously only original concave. I noticed that on the original concave floor in Bullet sphere and ray didn't lose ground but on concave they started to flicker. Also added floor segmentation should give extra test purpose.
The moving platform now has a movement up and down. It will be needed to test also ground connection on the movement.

2021-07-14 01:17 UTC, pouleyKetchoupp requested changes
Looks great!

For the ground check test, it would be nice to be able to switch between concave and convex floor with an option menu instead of having to wait for the objects to move all the way through one then the other, for faster testing.

2021-07-14 01:17 UTC, pouleyKetchoupp commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +const SHAPE_CILINDER = "Collision shapes/Cilinder"
Typo: `CYLINDER` instead of `CILINDER` (in the scene as well).

2021-07-16 19:43 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_moving_platform.gd
> +const SHAPE_CILINDER = "Collision shapes/Cilinder"
Done.

2021-07-16 19:45 UTC, nezvers commented
Now includes options menu for switching floor sizes (small, big) and collision shape (Convex, concave, box).

2021-07-16 20:00 UTC, pouleyKetchoupp requested changes

2021-07-16 20:09 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_rigidbody_ground_check.tscn
> +visible = false
Done.

2021-07-16 20:10 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_rigidbody_ground_check.tscn
>  [node name="Camera" type="Camera" parent="."]
Done.

2021-07-16 20:10 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_rigidbody_ground_check.gd
> +	_floor_shapes[SHAPE_CONVEX+"Small"] = get_packed_scene($"Floors/ConvexSmall")
Done.

2021-07-16 20:32 UTC, pouleyKetchoupp approved these changes
Looks good!

2021-07-16 22:53 UTC, aaronfranke approved these changes
Overall this looks very good!

Why are the collision shapes scaled by `0.8`? Is it to test scaled collision shapes? It's generally discouraged to scale physics stuff in Godot, but if it's for testing purposes it 100% makes sense.

I left some nit-picky suggestions below. I set this as approved because even if you don't act on them I will still merge this as this PR is very good.

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_ground_check.tscn
> +transform = Transform( 0.8, 0, 0, 0, -3.49691e-08, -0.8, 0, 0.8, -3.49691e-08, 0, 0, 0 )
```suggestion
transform = Transform( 0.8, 0, 0, 0, 0, -0.8, 0, 0.8, 0, 0, 0, 0 )
```

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_moving_platform.tscn
> +transform = Transform( 1, 0, 0, 0, -4.37114e-08, -1, 0, 1, -4.37114e-08, 0, 0.8, 0 )
```suggestion
transform = Transform( 1, 0, 0, 0, 0, -1, 0, 1, 0, 0, 0.8, 0 )
```

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
> +transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 3, 1.97795, 0 )
```suggestion
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 3, 2, 0 )
```

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
> +transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, -3, 1.0034, 0 )
```suggestion
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, -3, 1, 0 )
```

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
> +transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1.0034, 0 )
```suggestion
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0 )
```

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
> +transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, -6, 1.0034, 0 )
```suggestion
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, -6, 1, 0 )
```

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
> +transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 6, 1.0034, 0 )
```suggestion
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 6, 1, 0 )
```

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
> +transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 8, 1.0034, 0 )
```suggestion
transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 8, 1, 0 )
```

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
> +transform = Transform( 0.8, 0, 0, 0, -3.49691e-08, -0.8, 0, 0.8, -3.49691e-08, 0, 0, 0 )
```suggestion
transform = Transform( 0.8, 0, 0, 0, 0, -0.8, 0, 0.8, 0, 0, 0, 0 )
```

2021-07-16 22:53 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_ground_check.tscn
> +transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1 )
```suggestion
```

This doesn't need to be translated (and with the translation gone, the transform is the identity so it's not stored).

2021-07-16 22:56 UTC, aaronfranke commented on 3d/physics_tests/tests/functional/test_rigidbody_ground_check.gd
> +	var floor_inst = _floor_shapes[_current_floor_name+_floor_size].instance()
```suggestion
	var floor_inst = _floor_shapes[_current_floor_name + _floor_size].instance()
```

2021-07-17 09:49 UTC, nezvers commented on 3d/physics_tests/tests/functional/test_moving_platform.tscn
> +transform = Transform( 1, 0, 0, 0, 1, 0, 0, 0, 1, -7, -4.23538, 0 )
It's a moving platform, while moving it will go all kinds of float numbers.

2021-07-17 17:00 UTC, aaronfranke approved these changes

2021-07-17 17:00 UTC, merged