Fix leaked object - Label
godotengine/godot-demo-projects pull request #648
Opened 2021-09-01 18:21 UTC by gunnarahlberg

This fixes a warning of leaked instances.

"WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2132."

seems to be the Label.new() that was leaked.

2021-09-01 18:25 UTC, gunnarahlberg commented
And, this is my first look at Godot, really nice work and super easy to get me started. The error message was a small surprise, but the Godot ergonomics are so nice, it was easy to make the fix. 

Keep shining!

2021-09-01 18:29 UTC, Calinou commented on gui/theming_override/test.gd
> +# Save the label color so it can be resetted
```suggestion
# Save the label color so it can be reset.
```

2021-09-01 18:38 UTC, aaronfranke requested changes

2021-09-01 18:38 UTC, aaronfranke commented on gui/theming_override/test.gd
> -
Don't remove this, the GDScript style guide says that functions should be preceded by 2 empty lines.

2021-09-01 18:38 UTC, aaronfranke commented on gui/theming_override/test.gd
> +
Don't add this, the file should have exactly one `\n` at the end. This addition makes it two.

2021-09-02 09:58 UTC, gunnarahlberg commented on gui/theming_override/test.gd
> +
Thx!  Updated and fixed f7db9665917bdc8745cfe90f00e8147550eed751

2021-09-02 09:58 UTC, gunnarahlberg commented on gui/theming_override/test.gd
> -
Thx!  Updated and fixed f7db9665917bdc8745cfe90f00e8147550eed751

2021-09-13 05:04 UTC, aaronfranke approved these changes

2021-09-13 05:05 UTC, merged