Add a 3D Rigidbody character demo
godotengine/godot-demo-projects pull request #675
Opened 2022-01-02 23:36 UTC by alan-man

https://github.com/godotengine/godot-demo-projects/issues/669
Add a 3D Rigidbody character demo.

2022-01-27 18:46 UTC, aaronfranke requested changes
Sorry for the long time before reviewing this. This is just a surface-level review, I plan to give a more detailed review later after these comments are addressed.

2022-01-27 18:46 UTC, aaronfranke commented on 3d/rigidbody_character/README.md
> +Alan T.
Remove this section. The Git history already credits you, and it would be difficult to list every author.

2022-01-27 18:46 UTC, aaronfranke commented on 3d/rigidbody_character/level.gd
> +	pass
This function does nothing, so we can remove it.

2022-01-27 18:46 UTC, aaronfranke commented on 3d/rigidbody_character/player/cubio.gd
> +func _on_tcube_body_entered(body):
Be sure to follow the [GDScript style guide](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html).

* Functions should have two empty lines between them.
* Function names should be `snake_case`.

2022-01-27 18:46 UTC, aaronfranke commented on 3d/rigidbody_character/player/follow_camera.gd
> +# Member variables
Not a necessary comment.

Remove the blank line at the start of the file.

By the way, I'm aware that these problems also exist in KinematicCharacter3D, you are welcome to fix it there too.

2022-01-27 18:46 UTC, aaronfranke commented on 3d/rigidbody_character/player/follow_camera.gd
> +		delta_pos.y = min_height
```suggestion
	delta_pos.y = clamp(delta_pos.y, min_height, max_height)
```

By the way, I'm aware that this code also exists in KinematicCharacter3D, you are welcome to fix it there too.

2022-01-27 18:46 UTC, aaronfranke commented on 3d/rigidbody_character/level.gd
> +	var new_rb = rb.instance()
I haven't tested, but I think we don't need to store the preload in a variable. Also, the file should be renamed to be lowercase and use full words, perhaps `cube_rigidbody.tscn` or just `cube.tscn`

```suggestion
	var cube = preload("res://cube_rigidbody.tscn").instance()
```

2022-02-05 03:32 UTC, alan-man commented on 3d/rigidbody_character/player/cubio.gd
> +func _on_tcube_body_entered(body):
Done

2022-02-05 03:42 UTC, alan-man commented
All done. Thank you

2022-02-13 19:28 UTC, aaronfranke requested changes
Overall it looks quite good.

Please apply the changes from this PR to this demo, to keep the visuals in sync: #672

You forgot to commit the `*.import` files. They contain important information which needs to be committed. The demo doesn't quite work right when I open it on my computer without these. Don't confuse these with the `.import/` folder which should not be committed.

2022-02-13 19:28 UTC, aaronfranke commented on 3d/rigidbody_character/README.md
> +
```suggestion
```

Too many empty lines at the end of the file. There should be exactly one `\n` at the end of the file. When displayed on GitHub, there will be no empty lines, when displayed in VS Code you will see one extra line number at the end.

2022-02-13 19:28 UTC, aaronfranke commented on 3d/rigidbody_character/README.md
> +Cubes as RigidBodies spawn in the map from above to show interaction with the player (jump on them, gently push them), which would be impossible with a KinematicBody.
```suggestion
Cubes as RigidBodies spawn in the map from above to show interaction
with the player (jump on them, gently push them), which would be
impossible with a KinematicBody.
```

2022-02-13 19:28 UTC, aaronfranke commented on 3d/rigidbody_character/cube_rigidbody.tscn
> +[node name="cubeRB" type="RigidBody"]
The name of this node should be improved.

2022-02-13 19:28 UTC, aaronfranke commented on 3d/rigidbody_character/player/cubio.gd
> +onready var rc = $RayCast
Prefer using whole words for variable names to keep the code maximally readable.

```suggestion
onready var raycast = $RayCast
```

2022-03-20 23:24 UTC, alan-man commented on 3d/rigidbody_character/README.md
> +
done

2022-03-20 23:26 UTC, alan-man commented on 3d/rigidbody_character/README.md
> +Cubes as RigidBodies spawn in the map from above to show interaction with the player (jump on them, gently push them), which would be impossible with a KinematicBody.
done

2022-03-20 23:29 UTC, alan-man commented on 3d/rigidbody_character/cube_rigidbody.tscn
> +[node name="cubeRB" type="RigidBody"]
done

2022-03-20 23:30 UTC, alan-man commented on 3d/rigidbody_character/player/cubio.gd
> +onready var rc = $RayCast
done

2022-03-21 04:24 UTC, aaronfranke commented
There is a hole at the top of the level:

![Screenshot from 2022-03-20 23-11-34](https://user-images.githubusercontent.com/1646875/159205119-0502e368-ce21-4528-a087-ffdde1b9394f.png)

Once that's fixed, the rest looks good, so you can squash the Git history and we can get this merged.

2022-03-24 22:43 UTC, aaronfranke approved these changes
Looks good, squashing-and-merging this.

2022-03-24 22:43 UTC, merged