Added Alpha effect to joystick indicators
godotengine/godot-demo-projects pull request #678
Opened 2022-01-23 16:24 UTC by ScorpionInc

Added alpha effect to joystick sprites via selfmodulator color on the canvasitem.

2022-01-23 16:26 UTC, ScorpionInc commented
This is more a visual thing to make it easier to see the non-binary input values as alpha values for the joysticks. However analog triggers don't have this yet as they are treated more as a button. Not really needed just thought it might be liked if not no worries it can just be closed but thought I'd share. Hope your having a good day out there. o/

2022-01-23 17:21 UTC, Calinou requested changes

2022-01-23 17:21 UTC, Calinou commented on misc/joypads/joypads.gd
> +	var nextSelfModulatedColor = Color.white
Variable names should use `snake_case`, not `camelCase`.

2022-01-23 17:21 UTC, Calinou commented on misc/joypads/joypads.gd
> +				#Set button alpha self_modulator for the button CanvasItem to the absolute value of the axis strength.
This comment is redundant, as it repeats what is being done below. You can remove it entirely:

```suggestion
```

Also, can't you set `joypad_axes.get_node(str(axis) + "+").self_modulate.a` directly to avoid using an intermediate variable?

2022-01-23 17:21 UTC, Calinou commented on misc/joypads/joypads.gd
> +				#Set button alpha self_modulator for the button CanvasItem to the absolute value of the axis strength.
Same as above.

2022-01-23 17:21 UTC, Calinou commented on misc/joypads/joypads.gd
> +		var scaledAlphaValue = (abs(axis_value) - DEADZONE) / (1.0 - DEADZONE)
Variable names should use snake_case, not camelCase.

2022-01-23 17:45 UTC, ScorpionInc commented
The comments and intermediate variable were meant more for readability for me during testing, but were/are unneeded clutter which should have been caught. Sorry about that, they have been removed and hopely ready for another review.

2022-01-23 17:56 UTC, aaronfranke commented on misc/joypads/joypads.gd
> +				joypad_axes.get_node(str(axis) + "+").self_modulate.a = scaled_alpha_value# Preserves non-alpha color channels(Not used here.)
```suggestion
				# Transparent white modulate, non-alpha color channels are not changed here.
				joypad_axes.get_node(str(axis) + "+").self_modulate.a = scaled_alpha_value
```

2022-01-23 17:56 UTC, ScorpionInc commented on misc/joypads/joypads.gd
> +				joypad_axes.get_node(str(axis) + "+").self_modulate.a = scaled_alpha_value# Preserves non-alpha color channels(Not used here.)
Sounds good to me :)

2022-01-23 18:20 UTC, aaronfranke commented
Looks good to me. I haven't tested it but I assume it works and the style looks good. It could use a squash of the history though, see this article for more information: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

(If you don't do this, we can also do it, but it's better practice if the author does it)

2022-01-23 18:30 UTC, ScorpionInc commented
Never did a history squash before. I look forward to learning it :) Brb and thank you for your time.

2022-01-23 18:42 UTC, Calinou commented
I tested this PR locally and it works as expected :slightly_smiling_face:

2022-01-23 19:39 UTC, ScorpionInc commented
I think I did it wrong one sec...

2022-01-23 19:45 UTC, ScorpionInc commented
Is 3 commits okay? I can also try it again.

2022-01-23 20:37 UTC, aaronfranke commented
You're getting closer, keep trying!

2022-01-23 21:54 UTC, ScorpionInc commented
I think I got it :) Even managed to learn a bit on the way. ;p

2022-01-23 22:21 UTC, aaronfranke approved these changes

2022-01-24 15:09 UTC, ScorpionInc commented
I got the trigger indicators to fade properly but still act as a button as far as the highlighting goes. I know we just got this one all pretty with the commits. Should I make the changes and do the squash again or maybe as a seperate pull request? Sorry if this is a dumb question.

2022-01-24 17:45 UTC, aaronfranke commented
Feel free to keep changing this PR if you found something that works better.

2022-01-24 20:48 UTC, ScorpionInc commented
Hmm it seems I may have found a bug, but I'm unsure. The code is correct as it iterated from 0->9 step:1 length:10 as expected for all supported axis. However if I'm understanding this right there is no JOY_AXIS_10 defined within https://docs.godotengine.org/en/stable/classes/class_@globalscope.html which makes me think that this axis is either unneeded or for future expansion? I found something simular for the buttons as they only go from 0->22 length: 23. Again I'm assuming present for future expansion

2022-01-24 20:52 UTC, ScorpionInc commented
A quick fix would be to change: `for axis in range(JOY_AXIS_MAX):` into `for axis in range(int(min(JOY_AXIS_MAX,11))):` to allow for future expansion like the button grid does and then to change the color of the text manually. Thoughts?

2022-01-24 21:42 UTC, aaronfranke commented
@ScorpionInc Axis and button indexes above those values are unused. They're unused in this demo (not bound to any node in the UI), unused in the constants in Godot, unused in XInput, and unused in SDL2 (Godot uses the SDL2 controller mappings). If an input with a higher index is given by some unusual controller, it might still work but it won't be displayed in the demo.

2022-01-24 23:00 UTC, ScorpionInc commented
Thank you for the clarification. :) So would it be okay to remove these until they are used, or should I  keep them in for future use?

2022-01-24 23:08 UTC, ScorpionInc commented
Eh I think I'll leave them as they don't hurt anything even if they aren't connected yet.

2022-01-24 23:31 UTC, ScorpionInc commented
Okay I think I am happy with these changes. If by chance available I'd like to ask for another review. Thanks as always for your time help and feedback. :)

2022-01-27 08:17 UTC, ScorpionInc commented
I feel like maybe the text highlighting for the axis should maybe be it's own pull request. I was thinking of removing it from this one and having it be seperate. Sorry for n00bish questions but I can't seem to figure out how to have more than one pull request open for the same repo at a time?

2022-01-27 08:27 UTC, aaronfranke commented
@ScorpionInc The problem preventing you from opening another PR is that you are using your repo's master branch. Instead, you should make new branches for each pull request, and never use your repo's master for any PRs.

If they are separate things, then a separate pull request would be appropriate.

2022-01-27 08:29 UTC, ScorpionInc commented
Thank you so much for the help and fast response I'll be looking into branches on forks. Sounds like another thing that I should have known. Hope you have a great day :)

2022-01-27 16:47 UTC, ScorpionInc commented
Rather than trying to seperate the two, and change the fork from this back to the godotengine:main branch I think I'll just close this pull request refork the whole thing then do the branches the right way. Would that mess up anything?

2022-01-27 16:56 UTC, aaronfranke commented
Closing and reforking is not how I would do it. You can make another branch without killing this PR. If you're worried about breaking things, we could also get this PR simplified and merged first, and then you can fix your branches.

2022-01-27 17:23 UTC, ScorpionInc commented
Alrighty I'll try the simplifing route then. Sorry if I'm being a bother

2022-02-13 21:41 UTC, aaronfranke commented
@ScorpionInc Any update? Let us know once you think this PR is in a good state and can be reviewed and merged.

Also, if you have Git troubles, we can always just squash this PR at merge time.

2022-02-14 20:59 UTC, ScorpionInc commented
Sorry for the delay job got me busy. Should be able to get this trimmed back down within the week.

2022-02-16 09:48 UTC, ScorpionInc commented
I think I'm still just terrible at squashing but I'll get there I hope. It says there are a bunch of changes but those are from squashing after I merged from upstream, Not sure how to fix it. Anyway, The code should be the same as the last time it was approved. But I'd like to ask for another review to ensure it still passes muster. Thanks as always for your time.

2022-02-16 09:49 UTC, ScorpionInc commented
Okay I think that fixed it, now it only shows the actual changes.

2022-02-20 19:50 UTC, aaronfranke approved these changes
Style looks good. I'm making the assumption that this still works well, but @Calinou can give a re-test if he wants. We'll do a squash-and-merge of this soon.

2022-02-20 20:50 UTC, Calinou commented
The effect is only working on the bottom and right arrows, not the top and left arrows:

https://user-images.githubusercontent.com/180032/154863808-ca5063f7-105e-46e0-a784-e6bfd4ffe744.mp4

2022-02-22 21:20 UTC, ScorpionInc commented
Good catch thank you for checking its always the little things. Should be fixed now. Going to squash again.

2022-02-23 14:05 UTC, ScorpionInc commented
Alright what a pain. When I was trying to squash the small change, git kept adding me as another to previous commits that I didn't touch. Then trying to either squash those, or drop them and remerge from master made all kinds of issues. Either I'm the fool(Which is probably the case) or this should be made more intuitive for noobish contributers. Anyway one of my attempts to fix it ended up dropping the commit somehow(Not sure how). So I readded the changes and am now attempting to reopen the pull.

2022-02-23 14:07 UTC, ScorpionInc commented
If I may ask for another review whenever a chance is available it should be good now but as I mentioned I seem to be quite the fool with git.

2022-02-24 20:40 UTC, Calinou approved these changes
Tested locally, it works as expected on all analog axes displayed by the demo.

2022-02-24 21:20 UTC, aaronfranke approved these changes

2022-02-24 21:21 UTC, merged

2022-02-24 21:22 UTC, aaronfranke commented
Thanks! Quick reminder, in the future make a separate branch for your PRs if you plan to open more PRs.

2022-02-24 21:24 UTC, ScorpionInc commented
Thank you both for all of your help. I'll be sure to use branches for any other proposed changes. thanks again.