Add a 3D settings demo (Graphical settings) for 4.0-dev
godotengine/godot-demo-projects pull request #713
Opened 2022-04-03 03:44 UTC by voylin

Could possible fix #600.
This demo has some of the basic graphical settings that game devs would want. I tried to keep it minimal because it's just a demo. I hope this is sufficient and that there are enough comments explaining everything. Everything works without any bugs or errors.

2022-04-03 05:19 UTC, voylin commented
Because this has to do with graphics, I guess that this has to be "Vulkan Clustered", right? I changed  the README file already, if it is not correct, please let me know!

2022-04-03 08:58 UTC, aaronfranke reviewed
The folder of this demo should be renamed to `graphics_settings`, such that the path is `3d/graphics_settings`.

2022-04-03 08:58 UTC, aaronfranke commented on 3d/3d_settings_menu/project.godot
> +config/name="3d Settings Menu"
```suggestion
config/name="3D Graphics Settings Demo"
```

2022-04-03 08:58 UTC, aaronfranke commented on 3d/3d_settings_menu/project.godot
> +window/size/viewport_height=1080
These values are too high. I appreciate the future proofing with making the viewport size start large, but in practice this is just cumbersome to work with, especially for users with smaller screens. We can probably just make this demo use Godot's default values of 1024x600, or maybe we could do 1280x720. Regardless, we expect that any demo will be able to scale up from its base resolution, this is only used for the size when designing the UI in the editor and the initial size of the window (and even then, the window size can be overridden using another setting if needed).

2022-04-03 08:58 UTC, aaronfranke commented on 3d/3d_settings_menu/settings.gd
> +	var default_size := Vector2(1920,1080)
Commas should have spaces after it. But also, it's questionable to redefine this value in script when it's already in project settings, this means that it has to be changed in multiple places. This should probably use `ProjectSettings.get_setting("name/of/setting/here")` to grab the value from project settings.

2022-04-03 09:06 UTC, aaronfranke commented on 3d/3d_settings_menu/.gitattributes
> +* text=auto eol=lf
Godot automatically generates these `.gitattributes` and `.gitignore` files (because of me), and in most cases where you have one repo per project we do want these, but for the Godot demo projects repo we have lots of projects in one repo so we already have repo-level configs for these and we don't want copies in each demo.

2022-04-03 09:26 UTC, voylin commented on 3d/3d_settings_menu/.gitattributes
> +* text=auto eol=lf
I'll take this in mind next time when I create a new demo to deselect the git option on the project creation screen. Thanks!

2022-04-03 09:54 UTC, aaronfranke reviewed
Some of the sides of these buttons are being cut off.

![Screenshot from 2022-04-03 04-45-58](https://user-images.githubusercontent.com/1646875/161421730-2be3a7ec-5702-4527-81ec-27bf2c3f0deb.png)

There are other settings that we should showcase in this demo. Some are nodes such as VoxelGI and ReflectionProbe. Some are WorldEnvironment settings such as SDFGI, SSAO, SSIL (looks like you already did this for SS reflections). It would also be good to showcase texture quality. Another one would be model quality (maybe using the GLTF auto-LOD system that @fire was working on). This will likely end up needing a menu with sections and a scroll bar.

This will also need a more detailed review from @Calinou to ensure that this includes what he was hoping for with a graphics settings demo. I would also appreciate if @Calinou can give thoughts on the current state, on what you've already done so far and on my suggestions, and maybe he has some other suggestions.

2022-04-03 09:54 UTC, aaronfranke commented on 3d/graphics_settings/settings.gd
> +	var new_size : Vector2
```suggestion
	var new_size: Vector2
```

etc. https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html

2022-04-03 10:39 UTC, voylin commented
I was able to fix the border cut-off by giving the option buttons a bit more space.
Ambient Occlusion is SSAO and indirect lightning is SSIL, I renamed these to this option to make it more clear.

At this moment there are some graphical errors because of the alpha stage of the engine I'm working on Godot 4.0 alpha-5.
Texture quality, model quality and lod is something I will look into doing after @Calinou also gave his opinion of what he wants to get added. In the meantime I'll do a bit more research about those kind of settings as I don't have any experience with those kind of settings before. 

Thank you for your input and advice!

2022-04-05 21:33 UTC, Calinou commented
The demo looks like a good starting point to me. Feel free to merge as-is and I'll make further changes in a future pull request.

2022-04-05 21:33 UTC, Calinou approved these changes

2022-04-06 00:15 UTC, aaronfranke requested changes
Overall this looks great, the code is well-documented. I did encounter some bugs but I think they're all Godot bugs, not bugs with this project. I have a suggestion for getting the viewport size from project settings, and then this can be squashed and merged. Bonus points if you squash it and rebase yourself.

2022-04-06 00:15 UTC, aaronfranke commented on 3d/graphics_settings/settings.gd
> +func _ready() -> void:
Let's cache this value in the ready function.

```suggestion
var viewport_start_size := Vector2()

func _ready() -> void:
	viewport_start_size.x = ProjectSettings.get_setting(&"display/window/size/viewport_width")
	viewport_start_size.y = ProjectSettings.get_setting(&"display/window/size/viewport_height")
```

2022-04-06 00:15 UTC, aaronfranke commented on 3d/graphics_settings/settings.gd
> +	new_size.y = ProjectSettings.get_setting(&"display/window/size/viewport_height")
```suggestion
	var new_size := viewport_start_size
```

2022-04-06 01:49 UTC, voylin commented on 3d/graphics_settings/settings.gd
> +	new_size.y = ProjectSettings.get_setting(&"display/window/size/viewport_height")
Thank you for the suggestion!
Can I ask a small question, I tried looking this up but the reason why I can't find anything is probably because I have no idea what it actually is called.
In connect functions and in this setting function we use '&', what is the reason for this?

2022-04-06 01:50 UTC, voylin commented
> Overall this looks great, the code is well-documented. I did encounter some bugs but I think they're all Godot bugs, not bugs with this project. I have a suggestion for getting the viewport size from project settings, and then this can be squashed and merged. Bonus points if you squash it and rebase yourself.

I think I earned myself some bonus points. ^o^

2022-04-06 02:56 UTC, aaronfranke approved these changes
> I think I earned myself some bonus points. ^o^

Well, you squashed, but did not rebase. The latter is optional but does make the Git history slightly easier to read.

2022-04-06 02:57 UTC, merged

2022-04-06 02:57 UTC, aaronfranke commented
Thanks!

2022-04-08 20:25 UTC, Calinou commented
The demo crashes as soon as I start it, both on 4.0alpha6 and latest `master`:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (bf153b82c73755bf898df9de33ac2116ebe914b9)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3d320) [0x7fc7a0c0e320] (??:0)
[2] Object::get(StringName const&, bool*) const (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:467)
[3] ProjectSettings::get_setting(String const&) const (/home/hugo/Documents/Git/godotengine/godot/core/config/project_settings.cpp:1117)
[4] void call_with_variant_args_retc_helper<__UnexistingClass, Variant, String const&, 0ul>(__UnexistingClass*, Variant (__UnexistingClass::*)(String const&) const, Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul>) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:705)
[5] void call_with_variant_args_retc_dv<__UnexistingClass, Variant, String const&>(__UnexistingClass*, Variant (__UnexistingClass::*)(String const&) const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:501)
[6] MethodBindTRC<Variant, String const&>::call(Object*, Variant const**, int, Callable::CallError&) (/home/hugo/Documents/Git/godotengine/godot/./core/object/method_bind.h:582)
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_vm.cpp:1742)
[8] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript.cpp:1539)
[9] bool Node::_gdvirtual__ready_call<false>() (/home/hugo/Documents/Git/godotengine/godot/./scene/main/node.h:233)
[10] Node::_notification(int) (/home/hugo/Documents/Git/godotengine/godot/scene/main/node.cpp:155)
[11] Node::_notificationv(int, bool) (/home/hugo/Documents/Git/godotengine/godot/./scene/main/node.h:45)
[12] CanvasItem::_notificationv(int, bool) (/home/hugo/Documents/Git/godotengine/godot/./scene/main/canvas_item.h:?)
[13] Control::_notificationv(int, bool) (/home/hugo/Documents/Git/godotengine/godot/./scene/gui/control.h:?)
[14] Object::notification(int, bool) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:848)
[15] Node::_propagate_ready() (/home/hugo/Documents/Git/godotengine/godot/scene/main/node.cpp:187)
[16] Node::_propagate_ready() (/home/hugo/Documents/Git/godotengine/godot/scene/main/node.cpp:178)
[17] Node::_set_tree(SceneTree*) (/home/hugo/Documents/Git/godotengine/godot/scene/main/node.cpp:?)
[18] SceneTree::initialize() (/home/hugo/Documents/Git/godotengine/godot/scene/main/scene_tree.cpp:399)
[19] OS_LinuxBSD::run() (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/os_linuxbsd.cpp:?)
[20] bin/godot.linuxbsd.tools.64.llvm(main+0x1c6) [0x42e5fb6] (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/godot_linuxbsd.cpp:68)
[21] /lib64/libc.so.6(__libc_start_main+0xd5) [0x7fc7a0bf8b75] (??:0)
[22] bin/godot.linuxbsd.tools.64.llvm(_start+0x2e) [0x42e5d2e] (??:?)
-- END OF BACKTRACE --
================================================================
```

The demo can be opened in the editor, but it will crash instantly on start before a single frame is even rendered.

2022-04-08 20:49 UTC, voylin commented
> 

Just downloaded alpha 6 to test if I have the same issue, but for me everything runs fine.

![Screenshot from 2022-04-09 05-46-19](https://user-images.githubusercontent.com/56970759/162527645-f5d1946e-0ef2-4a90-b16f-5d12fe15f133.png)

But I do get errors like these:
`ERROR: Condition "!rb" is true. Returning: false
   at: render_buffers_has_volumetric_fog (servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:2900)
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9435)`