Fixing GD Paint Issues in 4.0-dev
godotengine/godot-demo-projects pull request #741
Opened 2022-05-07 22:37 UTC by voylin

The clipping happened because the panel was see-through.
The saving is also fixed by changing some of the project settings.
To fix the issues from #734

2022-05-07 23:07 UTC, aaronfranke reviewed
Thanks for these fixes! It works well on my system. But the panel's background color seems a bit bright.

2022-05-07 23:07 UTC, aaronfranke commented on 2d/gd_paint/paint_root.tscn
> +bg_color = Color(0.254902, 0.286275, 0.294118, 1)
```suggestion
bg_color = Color(0.2, 0.2, 0.2, 1)
```

2022-05-07 23:33 UTC, voylin commented
> Thanks for these fixes! It works well on my system. But the panel's background color seems a bit bright.

You're welcome. I'm glad that I found out what was causing that strange saving bug.

2022-05-07 23:41 UTC, aaronfranke approved these changes

2022-05-07 23:44 UTC, aaronfranke requested changes

2022-05-07 23:44 UTC, aaronfranke commented on 2d/gd_paint/tools_panel.gd
> +	get_parent().find_child(^"DrawingAreaBG").modulate = color
Why was this changed? This should still be `get_node`.

2022-05-08 00:06 UTC, voylin commented on 2d/gd_paint/tools_panel.gd
> +	get_parent().find_child(^"DrawingAreaBG").modulate = color
Aah that got changed because I was testing with viewport containers instead. It was during the testing of SubViewports that I discovered the solution. Will change it right now!

2022-05-08 00:09 UTC, aaronfranke approved these changes

2022-05-08 01:19 UTC, aaronfranke approved these changes

2022-05-08 01:19 UTC, merged

2022-05-08 01:19 UTC, aaronfranke commented
Thanks for all of your work!

2022-05-08 01:58 UTC, voylin commented
> Thanks for all of your work!

I'm happy that I can help. \^^/