[4.0] Clean up and fix Truck Town
godotengine/godot-demo-projects pull request #767
Opened 2022-08-25 22:05 UTC by jtnicholl

I've cleaned up the Truck Town demo and gotten it fully working.
I moved all of the mesh data out of the .tscn files into binary resource files. Except for the town itself, which I brought into Blender and did a clean up on; I fixed the broken normals that were messing up the lighting and also de-duplicated the meshes. It's now a .glb file.
I also did a bit of code cleanup, made the file paths lowercase, updated the screenshot and icon, and turned on FXAA.

2022-08-25 22:12 UTC, aaronfranke reviewed
This looks really good from a quick review, thank you!

I noticed that the `choose_*` files got bigger. You can use a tool called `oxipng` to compress PNG images, the command is `oxipng -o6 --strip all --zopfli --fix`.

2022-08-25 22:12 UTC, aaronfranke commented on 3d/truck_town/vehicle.gd
> +var _steer_target := 0.0
Cleaning up the literals for things that should be floats is very helpful, if you want you can do it in a few more places, like changing `if speed < 5 and speed != 0:` below to `if speed < 5.0 and speed != 0.0:`

2022-08-25 23:18 UTC, jtnicholl commented
> I noticed that the `choose_*` files got bigger. You can use a tool called `oxipng` to compress PNG images, the command is `oxipng -o6 --strip all --zopfli --fix`.

That's what I did, in order to optimize the new icon and screenshot. I ran it over the rest of the files again and there was no difference.
Viewing the commit in GitHub it seems to be saying the files went up in size by their total size, I think that's a bug in GitHub. The only change I made to those files was move them.

2022-08-26 17:05 UTC, aaronfranke requested changes
Did a quick test. There are some problems. The trucks do not spawn in the correct place, and the joints are missing. These problems do not exist on the current 4.0-dev branch which [has Truck Town ported](https://github.com/godotengine/godot-demo-projects/pull/696) already.

2022-08-26 17:31 UTC, jtnicholl commented
Are you sure you're on the right branch? The joints are working fine when I test it. But when I test the current 4.0-dev branch the joints aren't attached. Also, the trucks are spawning in the same place on both branches. Where are they supposed to spawn?

2022-08-26 17:44 UTC, jtnicholl commented
Ok, I just tested with alpha 14 instead of building from latest master, and now I'm seeing the issues you mentioned. It looks like the node params on Joint got renamed some time between alpha 14 and now. As for spawning in the wrong location, I don't know why that's happens, but it's fixed if you build from latest master.

2022-08-26 18:26 UTC, aaronfranke commented
You're right, it does work with master. However, with master I noticed that there are weird shadows everywhere? It happens on the 4.0-dev branch and with your PR with Godot master, but it doesn't happen with alpha 14. Anyway, this isn't a problem with your PR, so we can merge it after alpha 15 is released.

<img width="1165" alt="Screen Shot 2022-08-26 at 1 21 38 PM" src="https://user-images.githubusercontent.com/1646875/186967953-4b560fdd-9bb3-4313-9bad-9fff6b5fa679.png">

2022-08-26 18:32 UTC, Calinou commented
>  It happens on the 4.0-dev branch and with your PR with Godot master, but it doesn't happen with alpha 14.

This is a engine bug from the recent merge of octahedral compression.

2022-08-30 01:51 UTC, jtnicholl commented
I just cleaned up the vehicles and put them in a glb file as well, to fix the octahedral compression errors, a hole on the tow truck, and some backwards normals on the trailer. Also improved the wheels and branded the sides of the trailer with a waiting for Godot joke.

2022-08-30 17:52 UTC, aaronfranke approved these changes

2022-08-30 17:52 UTC, merged

2022-08-30 18:07 UTC, aaronfranke commented
Thanks! I made a follow-up PR: #768.