Update multiplayer pong to godot 4 beta 5
godotengine/godot-demo-projects pull request #792
Opened 2022-11-22 18:36 UTC by scriptsengineer

2022-12-01 11:16 UTC, Faless requested changes
See my comments on the preferred RPC syntax, other RPCs not touched by the code should also be updated to that format.

2022-12-01 11:16 UTC, Faless commented on networking/multiplayer_pong/logic/paddle.gd
> +		rpc("set_pos_and_motion", position, _motion)
```suggestion
		set_pos_and_motion.rpc(position, _motion)
```

2022-12-01 11:16 UTC, Faless commented on networking/multiplayer_pong/logic/paddle.gd
>  		area.rpc("bounce", left, randf())
```suggestion
		area.bounce.rpc(left, randf())
```

2022-12-03 12:20 UTC, scriptsengineer commented
Update all rpcs with new syntax: [3cab28e](https://github.com/godotengine/godot-demo-projects/pull/792/commits/3cab28e47cf20a2a3d2013cfe7ee59fd7bb5f04b)

2022-12-03 17:40 UTC, Faless approved these changes
Looks good now :+1: , thanks for updating the demo :trophy: .
Note that, before we can merge, you will have to squash you commits together.
See here for more info: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

2022-12-03 18:11 UTC, scriptsengineer commented
Successfully squashed commits

2022-12-03 20:45 UTC, merged

2022-12-03 20:46 UTC, Faless commented
Thanks!