Update projects to Godot 3.5
godotengine/godot-demo-projects pull request #827
Opened 2023-01-22 02:13 UTC by moth-boi

This PR updates the demos to Godot 3.5. I opened and saved all scenes and tested each project in Godot 3.5.1. I also included some bug fixes and removed some unnecessary code.

2023-01-22 11:16 UTC, Calinou requested changes
Please remove the `[mono]` assembly name changes in `project.godot` for projects that don't use C#/Mono.

After doing this, this PR should be good to merge.

2023-01-22 11:19 UTC, moth-boi commented
@Calinou Yes, I already know from Aaron, I'm working on that plus I'm fixing formatting of every GDScript.

2023-01-23 16:59 UTC, aaronfranke approved these changes

2023-01-23 17:24 UTC, Calinou approved these changes
Thanks! Great work :slightly_smiling_face:

2023-01-23 17:24 UTC, merged