Change @warnings to use a string identifier
godotengine/godot-demo-projects pull request #842
Opened 2023-02-10 16:21 UTC by Scimon

Tested in Godot 4 rc1.

2023-02-10 16:22 UTC, aaronfranke commented on audio/bpm_sync/bpm_sync.gd
> +	@warning_ignore('integer_division')
```suggestion
	@warning_ignore("integer_division")
```

2023-02-10 16:48 UTC, Calinou requested changes
There are several warning ignores not using quotes:

```
❯ rg -i "warning_ignore"
audio/spectrum/show_spectrum.gd
14:	@warning_ignore(integer_division)

3d/voxel/settings.gd
10:@warning_ignore(unused_private_class_variable)

audio/bpm_sync/bpm_sync.gd
45:	@warning_ignore(integer_division)
```

Please also change them in this pull request.

Also, is this change recommended by the GDScript style guide, or was this a recent breaking change in GDScript?

2023-02-10 16:57 UTC, Scimon commented
I opened the demo up in 4.0rc1 and it crashed due to that error so I figured I'd fix it. 
I didn't look for that use of warning ignore in other location because I was planning on doing demos on a case by case basis.

2023-02-10 17:01 UTC, Scimon commented
Sorry about the single quotes day job is Perl and general style is to use single quotes unless you need string interpolation.

2023-02-10 17:05 UTC, aaronfranke approved these changes

2023-02-10 17:06 UTC, aaronfranke commented
> or was this a recent breaking change in GDScript?

This. See #838 and https://github.com/godotengine/godot/issues/72218

2023-02-16 19:14 UTC, Calinou approved these changes
=
Thanks! Congratulations for your first merged pull request :tada:

2023-02-16 19:14 UTC, merged

2023-02-16 19:20 UTC, Scimon commented
I'll try and work through some more demo's at the weekend. :)

On Thu, 16 Feb 2023, 19:14 Hugo Locurcio, ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Thanks! Congratulations for your first merged pull request 🎉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/godotengine/godot-demo-projects/pull/842#pullrequestreview-1302123946>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAATZ3QEGQXVO4PIR7ZZ5DDWXZ4CFANCNFSM6AAAAAAUX7NA34>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>