Add a 3D tonemapping and color correction demo
godotengine/godot-demo-projects pull request #857
Opened 2023-02-25 01:47 UTC by Calinou

This showcases various tonemapping operators and their interaction with several color correction textures (1D and 3D).

A script generating neutral 3D LUT textures is also included.

## Preview

2024-09-14 06:38 UTC, huwpascoe requested changes
This is a very nice demo. Only needs two changes for latest Godot.

2024-09-14 06:38 UTC, huwpascoe commented on 3d/tonemap_color_correction/neutral_luts/3d/create_neutral_3d_luts.gd
> +	var image = Image.create(
var image = Image.create_empty(

2024-09-14 06:38 UTC, huwpascoe commented on 3d/tonemap_color_correction/options.gd
> +	world_environment.environment.tonemap_mode = index
world_environment.environment.tonemap_mode = index as Environment.ToneMapper

2024-10-18 21:23 UTC, Calinou commented
This PR now integrates https://github.com/Calinou/godot-demo-projects/pull/4 courtesy of @allenwp 🙂

2025-01-10 19:11 UTC, Calinou commented
I've updated the PR to add AgX support.

2025-01-11 09:48 UTC, akien-mga approved these changes

2025-01-11 09:50 UTC, AThousandShips commented on 3d/tonemap_color_correction/options.gd
> +func _on_exposure_value_changed(value: float) -> void:
```suggestion

func _on_exposure_value_changed(value: float) -> void:
```

2025-01-12 21:38 UTC, allenwp commented
> I've updated the PR to add AgX support following the merge of [godotengine/godot#87260](https://github.com/godotengine/godot/pull/87260).

I think you accidentally reverted https://github.com/Calinou/godot-demo-projects/pull/4 ?

2025-01-12 23:23 UTC, Calinou commented
> I think you accidentally reverted [Calinou#4](https://github.com/Calinou/godot-demo-projects/pull/4) ?

Fixed.

2025-05-30 13:55 UTC, Calinou commented
Rebased and tested again on 4.4.1.stable, it works as expected. I've also added a project icon as it was previously missing.

Merging, since this was recently approved. Once https://github.com/godotengine/godot/pull/94496 is ready to merge, we can modify the demo to have HDR support and add more test scenes to better showcase HDR functionality.

2025-05-30 14:08 UTC, merged