Port dodge the creeps C# to Godot 4
godotengine/godot-demo-projects pull request #870
Opened 2023-03-02 11:29 UTC by van800

2023-03-02 13:46 UTC, raulsntos requested changes
Thank you very much for updating this demo!

I have a PR that updates the documentation tutorial for this demo, but I didn't update the demo yet so I appreciate it.
- https://github.com/godotengine/godot-docs/pull/6811

2023-03-02 13:46 UTC, raulsntos commented on mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
> +  </ItemGroup>
I'm guessing this is used by some third-party source generator, analyzer or completion provider? I'm not sure we want to add it to the project then.

2023-03-02 13:46 UTC, raulsntos commented on mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
> +    <TargetFramework>net6.0</TargetFramework>
`EnableDynamicLoading` is also added to the csproj when creating new projects.

```suggestion
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
```

2023-03-02 13:46 UTC, raulsntos commented on mono/dodge_the_creeps/HUD.cs
> +
Unnecessary new line.

2023-03-02 13:46 UTC, raulsntos commented on mono/dodge_the_creeps/Player.cs
> +    public int Speed = 400; // How fast the player will move (pixels/sec).
While you are changing this, would you mind making these public fields be properties instead?

```suggestion
    public int Speed { get; set; } = 400; // How fast the player will move (pixels/sec).
```

2023-03-02 13:46 UTC, raulsntos commented on mono/dodge_the_creeps/Player.cs
> +        GetNode<CollisionShape2D>("CollisionShape2D").SetDeferred("disabled", false);
```suggestion
        GetNode<CollisionShape2D>("CollisionShape2D").SetDeferred(CollisionShape2D.PropertyName.Disabled, false);
```

2023-03-02 14:02 UTC, van800 commented on mono/dodge_the_creeps/HUD.cs
> +
Weird, I don't see that line in my editor.

2023-03-02 14:08 UTC, dalexeev commented on mono/dodge_the_creeps/Player.cs
>          );
There is `Vector2.clamp()` method (I'm not sure about C#).

2023-03-02 14:25 UTC, van800 commented on mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
> +  </ItemGroup>
In Rider, if you don't include files in the csproj, it is harder to see them and edit them. I suppose the same would be in the Visual Studio.

2023-03-02 15:05 UTC, dalexeev commented on mono/dodge_the_creeps/Player.cs
> +        Position = Position.Clamp(Position, ScreenSize);
```suggestion
        Position = Position.Clamp(Vector2.Zero, ScreenSize);
```

2023-03-02 15:18 UTC, raulsntos commented on mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
> +  </ItemGroup>
Ah, I see. I don't know about Visual Studio since I don't use it. Is it useful to edit these files manually from the IDE though?

2023-03-02 15:20 UTC, raulsntos commented on mono/dodge_the_creeps/HUD.cs
> +
Perhaps you could try editing the file on a different editor, or committing this suggestion:

```suggestion
```

2023-03-02 15:22 UTC, raulsntos commented on mono/dodge_the_creeps/Player.cs
> +    public Vector2 ScreenSize; // Size of the game window.
Another public field that should be a property.

```suggestion
    public Vector2 ScreenSize { get; set; } // Size of the game window.
```

2023-03-02 16:45 UTC, van800 commented on mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
> +  </ItemGroup>
When I was updating this example, I had to edit them a lot.

2023-03-02 16:52 UTC, van800 commented on mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
> +  </ItemGroup>
There is also a [gdscript plugin](https://plugins.jetbrains.com/plugin/13107-gdscript) for Rider, which has some features working, when scenes are included in the csproj.

2023-03-03 19:31 UTC, raulsntos commented on mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
> +  </ItemGroup>
I feel like plugins should be able to recommend users to add these to the csproj if they need it.

For example, when you open a C# project in VSCode you get a little notification that asks you if you want to add `tasks.json` and `build.json` files to configure debugging:

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/3903059/222808769-88f0a78e-b7d7-4198-9a1f-3b5187d33234.png)

</details>

---

> When I was updating this example, I had to edit them a lot.

Yes, but I'm assuming this is only common when porting projects between major versions which should be pretty rare. Otherwise, if there are any changes between minor versions, the project converter should be able to do it for you.

Also, doesn't Rider allow you to edit these files without adding them to the csproj? Maybe changing the explorer view to FileSystem?

![image](https://user-images.githubusercontent.com/3903059/222809897-1d84b09d-210d-423a-9692-f3941c413568.png)

2023-03-03 20:35 UTC, van800 commented on mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
> +  </ItemGroup>
1. There is at least one feature in Rider, which would only work with scenes added to the csproj. Run game with the scene.
![image](https://user-images.githubusercontent.com/1482681/222822758-017d628b-d868-4f4b-b225-a77dc1f64255.png)

2. I can't check Visual Studio for now, my windows machine is out-of-reach for some time.

2024-04-12 07:54 UTC, aaronfranke commented
Thank you for your work on this! I spent a few hours resolving the differences between this PR and #1000, ensuring best practices, no regressions, and consistency with the tutorial in the documentation.

Ultimately what I ended up with was quite different from both PRs. I have pushed the consolidations to both PRs so that you can view them, but I can only accept one PR. As an arbitrary choice, I will be accepting PR #870 and closing this one. I will squash-and-merge and include you as a co-author.

2024-04-12 07:54 UTC, closed without merging